# Constraint file for entity BANK0_14

# Outputs

set_property PACKAGE_PIN R18 [get_ports {SP7_LS_IRQ[0]}]
set_property PACKAGE_PIN T18 [get_ports SP7_PLL_STATUS]
set_property PACKAGE_PIN R15 [get_ports SP7_LS_NOR_PORESET]
set_property PACKAGE_PIN V14 [get_ports SP7_LS_DDR_RESET_B]
set_property PACKAGE_PIN V15 [get_ports SP7_LS_EMMC_RESET_B]
set_property PACKAGE_PIN T12 [get_ports LS_SPI_MISO]
set_property PACKAGE_PIN N13 [get_ports ZU_SP7_DMCU_RESET_STAT]
set_property PACKAGE_PIN M17 [get_ports SP7_GNSS_LS_UART_TX]
set_property PACKAGE_PIN M16 [get_ports SP7_GNSS_LS_UART_RX]
set_property PACKAGE_PIN M18 [get_ports SP7_GNSS_KU_UART_RX]
set_property PACKAGE_PIN N18 [get_ports SP7_GNSS_ZU_UART_RX]
set_property PACKAGE_PIN J14 [get_ports SP7_ZU_MODE_SPARE_LED_1]
set_property PACKAGE_PIN V13 [get_ports {SP7_DBG_UART_TX[0]}]
set_property PACKAGE_PIN U12 [get_ports {DMCU_RX_SP7_TX_UART_GPIO[0]}]
set_property PACKAGE_PIN R14 [get_ports LS_GNSS_1PPS]
set_property PACKAGE_PIN R16 [get_ports LS_GNSS_TP2_GPIO]
set_property PACKAGE_PIN P16 [get_ports KU_GNSS_1PPS]
set_property PACKAGE_PIN T14 [get_ports ZU_GNSS_1PPS]
set_property PACKAGE_PIN R13 [get_ports {DMCU_SP7_AUXB_CONFIG_CMD[0]}]
set_property PACKAGE_PIN M14 [get_ports DMCU_SP7_ZU_SPI_MISO]

# Inputs
set_property PACKAGE_PIN U16 [get_ports DMCU_MAIN_CLK_EN]
set_property PACKAGE_PIN V17 [get_ports DMCU_PLL_RESETB]
set_property PACKAGE_PIN T15 [get_ports LS_SP7_HRESET_B]
set_property PACKAGE_PIN U15 [get_ports LS_SP7_RESET_REQ_B]
set_property PACKAGE_PIN V16 [get_ports LS_SP7_ASLEEP]
set_property PACKAGE_PIN T13 [get_ports LS_SPI_MOSI]
set_property PACKAGE_PIN R11 [get_ports LS_SPI_CLK]
set_property PACKAGE_PIN T11 [get_ports LS_SP7_SPI_CS1]
set_property PACKAGE_PIN U11 [get_ports DMCU_SP7_PMCU_SPI_MOSI]
set_property PACKAGE_PIN V12 [get_ports DMCU_SP7_PMCU_SPI_CLK]
set_property PACKAGE_PIN L15 [get_ports SP7_PUDC]
set_property PACKAGE_PIN L16 [get_ports DMCU_SYSTEM_READY]
set_property PACKAGE_PIN L17 [get_ports DMCU_SP7_ZU_SPI_SCK]
set_property PACKAGE_PIN L18 [get_ports DMCU_DEV_SPI_SP7_CS]

set_property PACKAGE_PIN N14 [get_ports DMCU_SP7_ZU_SPI_MOSI]
set_property PACKAGE_PIN P18 [get_ports SP7_DBG_UART_RX]
set_property PACKAGE_PIN L13 [get_ports LS_PWRSEQ_RST_OUT_B_1V8]
set_property PACKAGE_PIN R12 [get_ports DMCU_LS_PORESET_CMD]
set_property PACKAGE_PIN P17 [get_ports DMCU_TX_SP7_RX_UART_GPIO]
set_property PACKAGE_PIN P14 [get_ports DMCU_FAN_CTRL]
set_property PACKAGE_PIN N15 [get_ports SP7_50MHZ_OSC_INPUT]
set_property PACKAGE_PIN P15 [get_ports DMCU_SP7_PMCU_SPI_AFE_PLL_CS2]
set_property PACKAGE_PIN R17 [get_ports DMCU_SP7_PMCU_SPI_DIG_PLL_CS1]
set_property PACKAGE_PIN P13 [get_ports SP7_DMCU_AUXB_CONFIG_STAT]







###############################################################################3


# Constraint file for entity BANK15

# Inputs
set_property PACKAGE_PIN G13 [get_ports ZU_DONE_2V5]
set_property PACKAGE_PIN K13 [get_ports ZU_ERROR_OUT_2V5]
set_property PACKAGE_PIN E16 [get_ports FAN_SP7_TACH_SENSOR_1]
set_property PACKAGE_PIN E17 [get_ports FAN_SP7_TACH_SENSOR_2]
set_property PACKAGE_PIN E14 [get_ports FAN_SP7_TACH_SENSOR_3]
set_property PACKAGE_PIN E15 [get_ports FAN_SP7_TACH_SENSOR_4]
set_property PACKAGE_PIN F18 [get_ports ZU_BOOT_STATUS_2V5]
set_property PACKAGE_PIN E18 [get_ports ZU_ERROR_STATUS_2V5]
set_property PACKAGE_PIN F13 [get_ports SP7_3V3_DIGPLL_PG]
set_property PACKAGE_PIN E13 [get_ports SP7_PLL_PWR_EN]
set_property PACKAGE_PIN H15 [get_ports SP7_3V3_AFEPLL_PG]
set_property PACKAGE_PIN G15 [get_ports FAN_SP7_TACH_SENSOR_5]
set_property PACKAGE_PIN B13 [get_ports SP7_3V3_OCXO_PG]
set_property PACKAGE_PIN A13 [get_ports SP7_3V3_VCXO_PG]
set_property PACKAGE_PIN H14 [get_ports FAN_SP7_TACH_SENSOR_6]
set_property PACKAGE_PIN K14 [get_ports OCXO_SP7_10M_DET_P]
set_property PACKAGE_PIN J15 [get_ports OCXO_SP7_10M_DET_N]
set_property PACKAGE_PIN D14 [get_ports AFE_VCXO_SP7_122M88_CLK_LVDS_P]
set_property PACKAGE_PIN D15 [get_ports AFE_VCXO_SP7_122M88_CLK_LVDS_N]
set_property PACKAGE_PIN F14 [get_ports SP7_10MHZ_LVDS_CLK_IN_P]
set_property PACKAGE_PIN F15 [get_ports SP7_10MHZ_LVDS_CLK_IN_N]

#[get_ports SP7_10MHZ_LVDS_CLK_IN_P] set_property DIFF_TERM TRUE[get_ports SP7_10MHZ_LVDS_CLK_IN_P]
#[get_ports SP7_10MHZ_LVDS_CLK_IN_P] set_property DIFF_TERM TRUE [get_ports SP7_10MHZ_LVDS_CLK_IN_N]

# Outputs
set_property PACKAGE_PIN H13 [get_ports {SP7_OSC_PWR_EN[0]}]
set_property PACKAGE_PIN H18 [get_ports {SP7_DMCU_IRQ[0]}]
set_property PACKAGE_PIN G18 [get_ports SP7_MAIN_CLK_STAT]
set_property PACKAGE_PIN K16 [get_ports SP7_DIG_PLL_SYNC]
set_property PACKAGE_PIN H16 [get_ports SP7_AFE_PLL_RESETB]
set_property PACKAGE_PIN H17 [get_ports SP7_AFE_PLL_SYNC]
set_property PACKAGE_PIN B14 [get_ports SP7_FAN_PWM_CTRL_5]
set_property PACKAGE_PIN A14 [get_ports SP7_FAN_PWM_CTRL_4]
set_property PACKAGE_PIN B15 [get_ports SP7_FAN_PWM_CTRL_6]
set_property PACKAGE_PIN A15 [get_ports SP7_FAN_PWM_CTRL_1]
set_property PACKAGE_PIN B16 [get_ports SP7_FAN_PWM_CTRL_2]
set_property PACKAGE_PIN A16 [get_ports SP7_FAN_PWM_CTRL_3]
set_property PACKAGE_PIN E12 [get_ports SP7_DIG_PLL_RESET]
set_property PACKAGE_PIN D12 [get_ports {SP7_LS_BST_EN_2V5[0]}]
set_property PACKAGE_PIN C13 [get_ports SP7_ZU_QSPI_CFG_MAP_2V5]
set_property PACKAGE_PIN B17 [get_ports SP7_LS_QSPI_CFG_MAP_2V5]
set_property PACKAGE_PIN A17 [get_ports {SP7_LS_TA_PROG_SFP_EN_2V5[0]}]
set_property PACKAGE_PIN C17 [get_ports {SP7_FAN_PWR_CTRL_EN[0]}]
set_property PACKAGE_PIN B18 [get_ports SP7_12V_OCXO_EN]
set_property PACKAGE_PIN D16 [get_ports SP7_LS_PORESET_CMD_2V5]
set_property PACKAGE_PIN D18 [get_ports {SP7_ZU_SPARE1P_CLKP_LVDS[0]}]
set_property PACKAGE_PIN C18 [get_ports {SP7_ZU_SPARE1N_CLKN_LVDS[0]}]
set_property PACKAGE_PIN G16 [get_ports {SP7_KU_SPARE1P_CLKP_LVDS[0]}]
set_property PACKAGE_PIN G17 [get_ports {SP7_KU_SPARE1N_CLKN_LVDS[0]}]
set_property PACKAGE_PIN J16 [get_ports LS_SP7_DMCU_RESET_STAT]
set_property PACKAGE_PIN C14 [get_ports {SP7_OCXO_INTB_EXT_REF[0]}]

# Inouts
set_property PACKAGE_PIN D17 [get_ports {J4124[0]}]

##############################################################################


# Constraint file for entity BANK34

# Outputs
set_property PACKAGE_PIN J6 [get_ports SP7_GNSS_RST_B]
set_property PACKAGE_PIN N5 [get_ports GNSS_UART_RXD_SP7_TXD]
set_property PACKAGE_PIN U3 [get_ports {SP7_SPARE_LED_2[0]}]
set_property PACKAGE_PIN U2 [get_ports {SP7_SPARE_LED_3[0]}]
set_property PACKAGE_PIN V3 [get_ports {SP7_SPARE_LED_4[0]}]
set_property PACKAGE_PIN K4 [get_ports {SP7_10M_CLK_REF_EN_B[0]}]
set_property PACKAGE_PIN L4 [get_ports OCXO_CLK_BUF_ENB]
set_property PACKAGE_PIN V7 [get_ports {SP7_10M_CLK_DAC_SEL[0]}]
set_property PACKAGE_PIN R5 [get_ports {SP7_10M_CLK_DAC_RESET[0]}]
set_property PACKAGE_PIN T4 [get_ports {SP7_10M_CLK_DAC_SDIN[0]}]
set_property PACKAGE_PIN T6 [get_ports {SP7_10M_CLK_DAC_SCLK[0]}]
set_property PACKAGE_PIN T5 [get_ports {SP7_10M_CLK_DAC_SYNC[0]}]
set_property PACKAGE_PIN R7 [get_ports SP7_DIG_PLL_SPI_CS0]
set_property PACKAGE_PIN U7 [get_ports SP7_AFE_PLL_SPI_CS1]
set_property PACKAGE_PIN U6 [get_ports SP7_PLL_SPI_CLK]
set_property PACKAGE_PIN L5 [get_ports SP7_KU_QSPI_CFG_MAP]
set_property PACKAGE_PIN M4 [get_ports {SP7_AUXB_PWR_EN[0]}]
set_property PACKAGE_PIN M2 [get_ports SP7_AFE_VCXO_ENB]
set_property PACKAGE_PIN P5 [get_ports SP7_JTAG_BUF_EN]

# Inputs
set_property PACKAGE_PIN N4 [get_ports GNSS_UART_TXD_SP7_RXD]
set_property PACKAGE_PIN V2 [get_ports SP7_DIP_SW_11]
set_property PACKAGE_PIN V5 [get_ports SP7_DIP_SW_12]
set_property PACKAGE_PIN V4 [get_ports SP7_DIP_SW_21]
set_property PACKAGE_PIN R4 [get_ports SP7_DIP_SW_22]
set_property PACKAGE_PIN V6 [get_ports LOC_10M_OSC_SP7_ENABLE]
set_property PACKAGE_PIN P2 [get_ports DIG_PLL_SP7_CLKSEL0]
set_property PACKAGE_PIN R2 [get_ports SP7_DIP_SW_32]
set_property PACKAGE_PIN R3 [get_ports AFE_PLL_SP7_CLKSEL0]
set_property PACKAGE_PIN K3 [get_ports DIG_PLL_SP7_LOCK_STAT]
set_property PACKAGE_PIN K1 [get_ports AFE_PLL_SP7_LOCK_STAT]
set_property PACKAGE_PIN R6 [get_ports SP7_AUXB_PWR_STAT]
set_property PACKAGE_PIN M1 [get_ports SP7_AUXB_CONFIG_STAT]
set_property PACKAGE_PIN N1 [get_ports LS_DDR4_TERM_PG]
set_property PACKAGE_PIN N3 [get_ports LS_2V5_DDR_PG]
set_property PACKAGE_PIN N2 [get_ports LS_TA_PROG_SFP_PG]
set_property PACKAGE_PIN P1 [get_ports {SP7_10M_SOURCE_SEL[0]}]
set_property PACKAGE_PIN R1 [get_ports GNSS_1PPS]
set_property PACKAGE_PIN T2 [get_ports GNSS_TP2]

# Inouts
set_property PACKAGE_PIN P7 [get_ports {SP7_ZU_3V3_GPIO_3[0]}]
set_property PACKAGE_PIN T3 [get_ports {SP7_ZU_3V3_GPIO_5[0]}]
set_property PACKAGE_PIN P6 [get_ports SP7_PLL_SPI_SDIO]
set_property PACKAGE_PIN L6 [get_ports {SP7_ZU_3V3_GPIO_1[0]}]
set_property PACKAGE_PIN U1 [get_ports {SP7_ZU_3V3_GPIO_2[0]}]
set_property PACKAGE_PIN M5 [get_ports {J4142[0]}]

set_property PACKAGE_PIN T1 [get_ports {SP7_AUXETH_PLL_RESET[0]}]
set_property PACKAGE_PIN K2 [get_ports SP7_AUXETH_PLL_GPIO4_LOCK]
set_property PACKAGE_PIN L1 [get_ports {SP7_AUXETH_PLL_HW_SW_CTRL}]
set_property PACKAGE_PIN K6 [get_ports {SP7_AUXETH_PLL_GPIO1_OE[0]}]

set_property PACKAGE_PIN M3 [get_ports {SP7_AUXB_CONFIG_CMD[0]}]


#MT25QU512ABB8E12-0SIT
#set_property CONFIG_MODE SPIx4 [current_design]
#set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
#set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
#set_property BITSTREAM.CONFIG.CONFIGRATE 31.9 [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property CFGBVS GND [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]
set_property BITSTREAM.CONFIG.CONFIGFALLBACK ENABLE [current_design]
set_property BITSTREAM.CONFIG.NEXT_CONFIG_ADDR 0x200000 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 22 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.TIMER_CFG 32'h0000DEA8 [current_design]

#set_false_path -from [get_clocks -of_objects [get_pins sp7_cal3_i/mmcm_50Mhz/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins cal3_sp7_i/hier_clock_measurments/clk_wiz_40m96_VCTCXO/inst/plle2_adv_inst/CLKOUT0]]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets LS_SP7_SPI_CS1_IBUF_inst/O]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets SP7_DIP_SW_22_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets sp7_cal3_i/mmcm_50Mhz/inst/clk_in1_sp7_cal3_mmcm_50Mhz_0]


set_property PACKAGE_PIN M13 [get_ports {spi_rtl_0_ss_io[0]}]
set_property PACKAGE_PIN K17 [get_ports spi_rtl_0_io0_io]
set_property PACKAGE_PIN K18 [get_ports spi_rtl_0_io1_io]
set_property PACKAGE_PIN L14 [get_ports spi_rtl_0_io2_io]
set_property PACKAGE_PIN M15 [get_ports spi_rtl_0_io3_io]



#BANK0_14

set_property IOSTANDARD LVCMOS18 [get_ports {SP7_LS_IRQ[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports SP7_PLL_STATUS]
set_property IOSTANDARD LVCMOS18 [get_ports DMCU_MAIN_CLK_EN]
set_property IOSTANDARD LVCMOS18 [get_ports DMCU_PLL_RESETB]
set_property IOSTANDARD LVCMOS18 [get_ports SP7_LS_NOR_PORESET]
set_property IOSTANDARD LVCMOS18 [get_ports LS_SP7_HRESET_B]
set_property IOSTANDARD LVCMOS18 [get_ports LS_SP7_RESET_REQ_B]
set_property IOSTANDARD LVCMOS18 [get_ports LS_SP7_ASLEEP]
#SP7_QSPI_FLASH_DATA0_MOSI
set_property IOSTANDARD LVCMOS18 [get_ports spi_rtl_0_io0_io] 
#SP7_QSPI_FLASH_DATA1_MISO
set_property IOSTANDARD LVCMOS18 [get_ports spi_rtl_0_io1_io] 
set_property IOSTANDARD LVCMOS18 [get_ports SP7_LS_DDR_RESET_B]
set_property IOSTANDARD LVCMOS18 [get_ports SP7_LS_EMMC_RESET_B]
set_property IOSTANDARD LVCMOS18 [get_ports LS_SPI_MISO]
set_property IOSTANDARD LVCMOS18 [get_ports LS_SPI_MOSI]
set_property IOSTANDARD LVCMOS18 [get_ports LS_SPI_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports LS_SP7_SPI_CS1]
set_property IOSTANDARD LVCMOS18 [get_ports {SP7_DBG_UART_TX[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports SP7_DBG_UART_RX]
set_property IOSTANDARD LVCMOS18 [get_ports LS_PWRSEQ_RST_OUT_B_1V8]
set_property IOSTANDARD LVCMOS18 [get_ports DMCU_LS_PORESET_CMD]
set_property IOSTANDARD LVCMOS18 [get_ports {DMCU_RX_SP7_TX_UART_GPIO[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports DMCU_TX_SP7_RX_UART_GPIO]
set_property IOSTANDARD LVCMOS18 [get_ports SP7_DMCU_AUXB_CONFIG_STAT]
set_property IOSTANDARD LVCMOS18 [get_ports {DMCU_SP7_AUXB_CONFIG_CMD[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports DMCU_SP7_PMCU_SPI_MOSI]
set_property IOSTANDARD LVCMOS18 [get_ports DMCU_SP7_PMCU_SPI_CLK]
# SP7_QSPI_FLASH_DATA2
set_property IOSTANDARD LVCMOS18 [get_ports spi_rtl_0_io2_io] 
# SP7_QSPI_FLASH_DATA3
set_property IOSTANDARD LVCMOS18 [get_ports spi_rtl_0_io3_io] 
set_property IOSTANDARD LVCMOS18 [get_ports SP7_PUDC]
set_property IOSTANDARD LVCMOS18 [get_ports DMCU_SYSTEM_READY]
set_property IOSTANDARD LVCMOS18 [get_ports DMCU_SP7_ZU_SPI_SCK]
set_property IOSTANDARD LVCMOS18 [get_ports DMCU_DEV_SPI_SP7_CS]
set_property IOSTANDARD LVCMOS18 [get_ports DMCU_SP7_ZU_SPI_MISO]
set_property IOSTANDARD LVCMOS18 [get_ports DMCU_SP7_ZU_SPI_MOSI]
# SP7_QSPI_FLASH_CSB
set_property IOSTANDARD LVCMOS18 [get_ports {spi_rtl_0_ss_io[0]}] 
set_property IOSTANDARD LVCMOS18 [get_ports ZU_SP7_DMCU_RESET_STAT]
set_property IOSTANDARD LVCMOS18 [get_ports SP7_GNSS_LS_UART_RX]
set_property IOSTANDARD LVCMOS18 [get_ports SP7_GNSS_LS_UART_TX]
set_property IOSTANDARD LVCMOS18 [get_ports SP7_GNSS_KU_UART_RX]
set_property IOSTANDARD LVCMOS18 [get_ports SP7_GNSS_ZU_UART_RX]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_ZU_MODE_SPARE_LED_1]
set_property IOSTANDARD LVCMOS18 [get_ports DMCU_FAN_CTRL]
set_property IOSTANDARD LVCMOS18 [get_ports SP7_50MHZ_OSC_INPUT]
set_property IOSTANDARD LVCMOS18 [get_ports LS_GNSS_1PPS]
set_property IOSTANDARD LVCMOS18 [get_ports LS_GNSS_TP2_GPIO]
set_property IOSTANDARD LVCMOS18 [get_ports DMCU_SP7_PMCU_SPI_AFE_PLL_CS2]
set_property IOSTANDARD LVCMOS18 [get_ports KU_GNSS_1PPS]
set_property IOSTANDARD LVCMOS18 [get_ports ZU_GNSS_1PPS]
set_property IOSTANDARD LVCMOS18 [get_ports DMCU_SP7_PMCU_SPI_DIG_PLL_CS1]



#BANK_15
set_property IOSTANDARD LVCMOS25 [get_ports ZU_DONE_2V5]
set_property IOSTANDARD LVCMOS25 [get_ports ZU_ERROR_OUT_2V5]
set_property IOSTANDARD LVCMOS25 [get_ports FAN_SP7_TACH_SENSOR_1]
set_property IOSTANDARD LVCMOS25 [get_ports FAN_SP7_TACH_SENSOR_2]
set_property IOSTANDARD LVCMOS25 [get_ports FAN_SP7_TACH_SENSOR_3]
set_property IOSTANDARD LVCMOS25 [get_ports FAN_SP7_TACH_SENSOR_4]
set_property IOSTANDARD LVCMOS25 [get_ports ZU_BOOT_STATUS_2V5]
set_property IOSTANDARD LVCMOS25 [get_ports ZU_ERROR_STATUS_2V5]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_3V3_DIGPLL_PG]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_PLL_PWR_EN]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_3V3_AFEPLL_PG]
set_property IOSTANDARD LVCMOS25 [get_ports FAN_SP7_TACH_SENSOR_5]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_3V3_OCXO_PG]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_3V3_VCXO_PG]
set_property IOSTANDARD LVCMOS25 [get_ports {SP7_OSC_PWR_EN[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports FAN_SP7_TACH_SENSOR_6]
set_property IOSTANDARD LVCMOS25 [get_ports {SP7_DMCU_IRQ[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_MAIN_CLK_STAT]
set_property IOSTANDARD LVCMOS25 [get_ports {SP7_ZU_SPARE1P_CLKP_LVDS[0]}]
set_property IOSTANDARD LVDS_25 [get_ports AFE_VCXO_SP7_122M88_CLK_LVDS_P]
set_property IOSTANDARD LVDS_25 [get_ports SP7_10MHZ_LVDS_CLK_IN_P]
set_property IOSTANDARD LVCMOS25 [get_ports {SP7_KU_SPARE1P_CLKP_LVDS[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_DIG_PLL_SYNC]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_AFE_PLL_RESETB]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_AFE_PLL_SYNC]
set_property IOSTANDARD LVCMOS25 [get_ports OCXO_SP7_10M_DET_N]
set_property IOSTANDARD LVCMOS25 [get_ports OCXO_SP7_10M_DET_P]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_FAN_PWM_CTRL_5]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_FAN_PWM_CTRL_4]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_FAN_PWM_CTRL_6]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_FAN_PWM_CTRL_1]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_FAN_PWM_CTRL_2]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_FAN_PWM_CTRL_3]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_DIG_PLL_RESET]
set_property IOSTANDARD LVCMOS25 [get_ports {SP7_LS_BST_EN_2V5[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_LS_QSPI_CFG_MAP_2V5]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_ZU_QSPI_CFG_MAP_2V5]
set_property IOSTANDARD LVCMOS25 [get_ports {SP7_LS_TA_PROG_SFP_EN_2V5[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SP7_FAN_PWR_CTRL_EN[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_12V_OCXO_EN]
set_property IOSTANDARD LVCMOS25 [get_ports SP7_LS_PORESET_CMD_2V5]
set_property IOSTANDARD LVCMOS25 [get_ports {J4124[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SP7_ZU_SPARE1N_CLKN_LVDS[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SP7_KU_SPARE1N_CLKN_LVDS[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SP7_OCXO_INTB_EXT_REF[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports LS_SP7_DMCU_RESET_STAT]

#BANK_34
set_property IOSTANDARD LVCMOS33 [get_ports SP7_GNSS_RST_B]
set_property IOSTANDARD LVCMOS33 [get_ports {SP7_ZU_3V3_GPIO_3[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports GNSS_UART_RXD_SP7_TXD]
set_property IOSTANDARD LVCMOS33 [get_ports GNSS_UART_TXD_SP7_RXD]
set_property IOSTANDARD LVCMOS33 [get_ports {SP7_SPARE_LED_2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SP7_SPARE_LED_3[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SP7_SPARE_LED_4[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports SP7_DIP_SW_11]
set_property IOSTANDARD LVCMOS33 [get_ports SP7_DIP_SW_21]
set_property IOSTANDARD LVCMOS33 [get_ports SP7_DIP_SW_12]
set_property IOSTANDARD LVCMOS33 [get_ports SP7_DIP_SW_22]
set_property IOSTANDARD LVCMOS33 [get_ports {SP7_ZU_3V3_GPIO_5[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SP7_10M_CLK_REF_EN_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports OCXO_CLK_BUF_ENB]
set_property IOSTANDARD LVCMOS33 [get_ports {SP7_10M_CLK_DAC_SEL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports LOC_10M_OSC_SP7_ENABLE]
set_property IOSTANDARD LVCMOS33 [get_ports {SP7_10M_CLK_DAC_RESET[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SP7_10M_CLK_DAC_SDIN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SP7_10M_CLK_DAC_SCLK[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SP7_10M_CLK_DAC_SYNC[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports DIG_PLL_SP7_CLKSEL0]
set_property IOSTANDARD LVCMOS33 [get_ports SP7_DIP_SW_32]
set_property IOSTANDARD LVCMOS33 [get_ports AFE_PLL_SP7_CLKSEL0]
set_property IOSTANDARD LVCMOS33 [get_ports {SP7_AUXETH_PLL_RESET[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports SP7_PLL_SPI_SDIO]
set_property IOSTANDARD LVCMOS33 [get_ports SP7_DIG_PLL_SPI_CS0]
set_property IOSTANDARD LVCMOS33 [get_ports SP7_AUXB_PWR_STAT]
set_property IOSTANDARD LVCMOS33 [get_ports SP7_AFE_PLL_SPI_CS1]
set_property IOSTANDARD LVCMOS33 [get_ports SP7_PLL_SPI_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports DIG_PLL_SP7_LOCK_STAT]
set_property IOSTANDARD LVCMOS33 [get_ports SP7_AUXETH_PLL_GPIO4_LOCK]
set_property IOSTANDARD LVCMOS33 [get_ports AFE_PLL_SP7_LOCK_STAT]
set_property IOSTANDARD LVCMOS33 [get_ports {SP7_AUXETH_PLL_HW_SW_CTRL}]
set_property IOSTANDARD LVCMOS33 [get_ports {SP7_AUXETH_PLL_GPIO1_OE[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SP7_ZU_3V3_GPIO_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports SP7_KU_QSPI_CFG_MAP]
set_property IOSTANDARD LVCMOS33 [get_ports {SP7_AUXB_PWR_EN[0]}]
# missing SP7_AUXETH_PLL_I2C_SCL
set_property IOSTANDARD LVCMOS33 [get_ports {SP7_AUXB_CONFIG_CMD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports SP7_AFE_VCXO_ENB]
set_property IOSTANDARD LVCMOS33 [get_ports SP7_AUXB_CONFIG_STAT]
set_property IOSTANDARD LVCMOS33 [get_ports LS_DDR4_TERM_PG]
set_property IOSTANDARD LVCMOS33 [get_ports LS_2V5_DDR_PG]
set_property IOSTANDARD LVCMOS33 [get_ports LS_TA_PROG_SFP_PG]
set_property IOSTANDARD LVCMOS33 [get_ports {SP7_10M_SOURCE_SEL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports GNSS_1PPS]
set_property IOSTANDARD LVCMOS33 [get_ports GNSS_TP2]
set_property IOSTANDARD LVCMOS33 [get_ports {SP7_ZU_3V3_GPIO_2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports SP7_JTAG_BUF_EN]
set_property IOSTANDARD LVCMOS33 [get_ports {J4142[0]}] 
# SP7_AUXETH_PLL_I2C_SDA






set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
