-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity parallel_to_AXI is
generic (
    C_M_AXI_GMEM_ADDR_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_BUSER_WIDTH-1 downto 0);
    wdata : IN STD_LOGIC_VECTOR (31 downto 0);
    wadd : IN STD_LOGIC_VECTOR (31 downto 0);
    rdata : OUT STD_LOGIC_VECTOR (31 downto 0);
    rdata_ap_vld : OUT STD_LOGIC;
    radd : IN STD_LOGIC_VECTOR (31 downto 0);
    cmd : IN STD_LOGIC_VECTOR (7 downto 0);
    sta : OUT STD_LOGIC_VECTOR (7 downto 0);
    sta_ap_vld : OUT STD_LOGIC;
    AXI : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of parallel_to_AXI is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "parallel_to_AXI_parallel_to_AXI,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7s25-csga324-2,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.807000,HLS_SYN_LAT=14,HLS_SYN_TPT=1,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1002,HLS_SYN_LUT=1035,HLS_VERSION=2020_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_iter0_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_ST_iter1_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter2_fsm_state3 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter3_fsm_state4 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter4_fsm_state5 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter5_fsm_state6 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter6_fsm_state7 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter7_fsm_state8 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter8_fsm_state9 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter9_fsm_state10 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter10_fsm_state11 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter11_fsm_state12 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter12_fsm_state13 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter13_fsm_state14 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter14_fsm_state15 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter1_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter2_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter3_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter4_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter5_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter6_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter7_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter8_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter9_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter10_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter11_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter12_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter13_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter14_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant C_M_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv8_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000011";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal ap_CS_iter0_fsm_state1 : STD_LOGIC;
    signal ap_CS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter1_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter2_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter2_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter3_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter3_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter4_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter4_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter5_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter5_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter6_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter6_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter7_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter7_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter8_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter8_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter9_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter9_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter10_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter10_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter11_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter11_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter12_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter12_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter13_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter13_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter14_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter14_fsm_state0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal gmem_AWVALID : STD_LOGIC;
    signal gmem_AWREADY : STD_LOGIC;
    signal gmem_WVALID : STD_LOGIC;
    signal gmem_WREADY : STD_LOGIC;
    signal gmem_ARVALID : STD_LOGIC;
    signal gmem_ARREADY : STD_LOGIC;
    signal gmem_RVALID : STD_LOGIC;
    signal gmem_RREADY : STD_LOGIC;
    signal gmem_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_RLAST : STD_LOGIC;
    signal gmem_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem_BVALID : STD_LOGIC;
    signal gmem_BREADY : STD_LOGIC;
    signal gmem_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal cmd_read_reg_274 : STD_LOGIC_VECTOR (7 downto 0);
    signal clear_flag_load_reg_283 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op62_writereq_state2 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal ap_CS_iter1_fsm_state2 : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal cmd_read_reg_274_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal clear_flag_load_reg_283_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op63_write_state3 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_CS_iter2_fsm_state3 : STD_LOGIC;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_CS_iter3_fsm_state4 : STD_LOGIC;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_CS_iter4_fsm_state5 : STD_LOGIC;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_CS_iter5_fsm_state6 : STD_LOGIC;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_CS_iter6_fsm_state7 : STD_LOGIC;
    signal cmd_read_reg_274_pp0_iter6_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal clear_flag_load_reg_283_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op69_writeresp_state8 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_predicate_op68_readreq_state8 : BOOLEAN;
    signal ap_block_state8_io : BOOLEAN;
    signal ap_CS_iter7_fsm_state8 : STD_LOGIC;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_CS_iter8_fsm_state9 : STD_LOGIC;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_CS_iter9_fsm_state10 : STD_LOGIC;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_CS_iter10_fsm_state11 : STD_LOGIC;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_CS_iter11_fsm_state12 : STD_LOGIC;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_CS_iter12_fsm_state13 : STD_LOGIC;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_CS_iter13_fsm_state14 : STD_LOGIC;
    signal cmd_read_reg_274_pp0_iter13_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal clear_flag_load_reg_283_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op76_read_state15 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14 : BOOLEAN;
    signal ap_CS_iter14_fsm_state15 : STD_LOGIC;
    signal clear_flag : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal gmem_blk_n_AW : STD_LOGIC;
    signal gmem_blk_n_W : STD_LOGIC;
    signal gmem_blk_n_B : STD_LOGIC;
    signal gmem_blk_n_AR : STD_LOGIC;
    signal gmem_blk_n_R : STD_LOGIC;
    signal cmd_read_read_fu_100_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal cmd_read_reg_274_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal cmd_read_reg_274_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal cmd_read_reg_274_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal cmd_read_reg_274_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal cmd_read_reg_274_pp0_iter7_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal cmd_read_reg_274_pp0_iter8_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal cmd_read_reg_274_pp0_iter9_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal cmd_read_reg_274_pp0_iter10_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal cmd_read_reg_274_pp0_iter11_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal cmd_read_reg_274_pp0_iter12_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal wdata_read_reg_278 : STD_LOGIC_VECTOR (31 downto 0);
    signal wdata_read_reg_278_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal clear_flag_load_load_fu_182_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal clear_flag_load_reg_283_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal clear_flag_load_reg_283_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal clear_flag_load_reg_283_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal clear_flag_load_reg_283_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal clear_flag_load_reg_283_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal clear_flag_load_reg_283_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal clear_flag_load_reg_283_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal clear_flag_load_reg_283_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal clear_flag_load_reg_283_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal clear_flag_load_reg_283_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_addr_1_reg_287 : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_addr_1_reg_287_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_addr_1_reg_287_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_addr_1_reg_287_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_addr_1_reg_287_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_addr_1_reg_287_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_addr_1_reg_287_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_addr_reg_293 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln34_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln34_reg_299 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln34_reg_299_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln34_reg_299_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln34_reg_299_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln34_reg_299_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln34_reg_299_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln34_reg_299_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln34_reg_299_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln34_reg_299_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln34_reg_299_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln34_reg_299_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln34_reg_299_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln34_reg_299_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln34_reg_299_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln324_1_fu_214_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln324_fu_252_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln324_1_fu_186_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal zext_ln324_1_fu_194_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln324_1_fu_198_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln324_1_fu_204_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal shl_ln_fu_224_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal zext_ln324_fu_232_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln324_fu_236_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln_fu_242_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal icmp_ln874_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter2_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter3_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter4_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter5_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter6_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter7_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter8_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter9_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter10_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter11_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter12_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter13_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter14_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_condition_593 : BOOLEAN;
    signal ap_condition_568 : BOOLEAN;

    component parallel_to_AXI_gmem_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_DW : INTEGER;
        USER_AW : INTEGER;
        USER_MAXREQS : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_RID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_RLAST : OUT STD_LOGIC;
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_WID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WLAST : IN STD_LOGIC;
        I_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC;
        I_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_BID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_BUSER : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    gmem_m_axi_U : component parallel_to_AXI_gmem_m_axi
    generic map (
        CONSERVATIVE => 0,
        USER_DW => 32,
        USER_AW => 32,
        USER_MAXREQS => 5,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_CACHE_VALUE)
    port map (
        AWVALID => m_axi_gmem_AWVALID,
        AWREADY => m_axi_gmem_AWREADY,
        AWADDR => m_axi_gmem_AWADDR,
        AWID => m_axi_gmem_AWID,
        AWLEN => m_axi_gmem_AWLEN,
        AWSIZE => m_axi_gmem_AWSIZE,
        AWBURST => m_axi_gmem_AWBURST,
        AWLOCK => m_axi_gmem_AWLOCK,
        AWCACHE => m_axi_gmem_AWCACHE,
        AWPROT => m_axi_gmem_AWPROT,
        AWQOS => m_axi_gmem_AWQOS,
        AWREGION => m_axi_gmem_AWREGION,
        AWUSER => m_axi_gmem_AWUSER,
        WVALID => m_axi_gmem_WVALID,
        WREADY => m_axi_gmem_WREADY,
        WDATA => m_axi_gmem_WDATA,
        WSTRB => m_axi_gmem_WSTRB,
        WLAST => m_axi_gmem_WLAST,
        WID => m_axi_gmem_WID,
        WUSER => m_axi_gmem_WUSER,
        ARVALID => m_axi_gmem_ARVALID,
        ARREADY => m_axi_gmem_ARREADY,
        ARADDR => m_axi_gmem_ARADDR,
        ARID => m_axi_gmem_ARID,
        ARLEN => m_axi_gmem_ARLEN,
        ARSIZE => m_axi_gmem_ARSIZE,
        ARBURST => m_axi_gmem_ARBURST,
        ARLOCK => m_axi_gmem_ARLOCK,
        ARCACHE => m_axi_gmem_ARCACHE,
        ARPROT => m_axi_gmem_ARPROT,
        ARQOS => m_axi_gmem_ARQOS,
        ARREGION => m_axi_gmem_ARREGION,
        ARUSER => m_axi_gmem_ARUSER,
        RVALID => m_axi_gmem_RVALID,
        RREADY => m_axi_gmem_RREADY,
        RDATA => m_axi_gmem_RDATA,
        RLAST => m_axi_gmem_RLAST,
        RID => m_axi_gmem_RID,
        RUSER => m_axi_gmem_RUSER,
        RRESP => m_axi_gmem_RRESP,
        BVALID => m_axi_gmem_BVALID,
        BREADY => m_axi_gmem_BREADY,
        BRESP => m_axi_gmem_BRESP,
        BID => m_axi_gmem_BID,
        BUSER => m_axi_gmem_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_ARVALID => gmem_ARVALID,
        I_ARREADY => gmem_ARREADY,
        I_ARADDR => gmem_addr_1_reg_287_pp0_iter6_reg,
        I_ARID => ap_const_lv1_0,
        I_ARLEN => ap_const_lv32_1,
        I_ARSIZE => ap_const_lv3_0,
        I_ARLOCK => ap_const_lv2_0,
        I_ARCACHE => ap_const_lv4_0,
        I_ARQOS => ap_const_lv4_0,
        I_ARPROT => ap_const_lv3_0,
        I_ARUSER => ap_const_lv1_0,
        I_ARBURST => ap_const_lv2_0,
        I_ARREGION => ap_const_lv4_0,
        I_RVALID => gmem_RVALID,
        I_RREADY => gmem_RREADY,
        I_RDATA => gmem_RDATA,
        I_RID => gmem_RID,
        I_RUSER => gmem_RUSER,
        I_RRESP => gmem_RRESP,
        I_RLAST => gmem_RLAST,
        I_AWVALID => gmem_AWVALID,
        I_AWREADY => gmem_AWREADY,
        I_AWADDR => gmem_addr_reg_293,
        I_AWID => ap_const_lv1_0,
        I_AWLEN => ap_const_lv32_1,
        I_AWSIZE => ap_const_lv3_0,
        I_AWLOCK => ap_const_lv2_0,
        I_AWCACHE => ap_const_lv4_0,
        I_AWQOS => ap_const_lv4_0,
        I_AWPROT => ap_const_lv3_0,
        I_AWUSER => ap_const_lv1_0,
        I_AWBURST => ap_const_lv2_0,
        I_AWREGION => ap_const_lv4_0,
        I_WVALID => gmem_WVALID,
        I_WREADY => gmem_WREADY,
        I_WDATA => wdata_read_reg_278_pp0_iter1_reg,
        I_WID => ap_const_lv1_0,
        I_WUSER => ap_const_lv1_0,
        I_WLAST => ap_const_logic_0,
        I_WSTRB => ap_const_lv4_F,
        I_BVALID => gmem_BVALID,
        I_BREADY => gmem_BREADY,
        I_BRESP => gmem_BRESP,
        I_BID => gmem_BID,
        I_BUSER => gmem_BUSER);





    ap_CS_iter0_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            else
                ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter10_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_iter10_fsm <= ap_ST_iter10_fsm_state0;
            else
                ap_CS_iter10_fsm <= ap_NS_iter10_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter11_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_iter11_fsm <= ap_ST_iter11_fsm_state0;
            else
                ap_CS_iter11_fsm <= ap_NS_iter11_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter12_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_iter12_fsm <= ap_ST_iter12_fsm_state0;
            else
                ap_CS_iter12_fsm <= ap_NS_iter12_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter13_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_iter13_fsm <= ap_ST_iter13_fsm_state0;
            else
                ap_CS_iter13_fsm <= ap_NS_iter13_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter14_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_iter14_fsm <= ap_ST_iter14_fsm_state0;
            else
                ap_CS_iter14_fsm <= ap_NS_iter14_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter1_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
            else
                ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter2_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
            else
                ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter3_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
            else
                ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter4_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_iter4_fsm <= ap_ST_iter4_fsm_state0;
            else
                ap_CS_iter4_fsm <= ap_NS_iter4_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter5_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_iter5_fsm <= ap_ST_iter5_fsm_state0;
            else
                ap_CS_iter5_fsm <= ap_NS_iter5_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter6_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_iter6_fsm <= ap_ST_iter6_fsm_state0;
            else
                ap_CS_iter6_fsm <= ap_NS_iter6_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter7_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_iter7_fsm <= ap_ST_iter7_fsm_state0;
            else
                ap_CS_iter7_fsm <= ap_NS_iter7_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter8_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_iter8_fsm <= ap_ST_iter8_fsm_state0;
            else
                ap_CS_iter8_fsm <= ap_NS_iter8_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter9_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_iter9_fsm <= ap_ST_iter9_fsm_state0;
            else
                ap_CS_iter9_fsm <= ap_NS_iter9_fsm;
            end if;
        end if;
    end process;


    clear_flag_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_start = ap_const_logic_0) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) or ((ap_const_boolean_1 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3)) or ((ap_const_boolean_1 = ap_block_state2_io) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) and (clear_flag_load_load_fu_182_p1 = ap_const_lv1_0) and (cmd_read_read_fu_100_p2 = ap_const_lv8_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1)) or (not(((ap_start = ap_const_logic_0) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) or ((ap_const_boolean_1 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3)) or ((ap_const_boolean_1 = ap_block_state2_io) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) and (clear_flag_load_load_fu_182_p1 = ap_const_lv1_0) and (cmd_read_read_fu_100_p2 = ap_const_lv8_2) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1)))) then 
                clear_flag <= ap_const_lv1_1;
            elsif (((not((cmd_read_read_fu_100_p2 = ap_const_lv8_3)) and not((cmd_read_read_fu_100_p2 = ap_const_lv8_1)) and not((cmd_read_read_fu_100_p2 = ap_const_lv8_2)) and not(((ap_start = ap_const_logic_0) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) or ((ap_const_boolean_1 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3)) or ((ap_const_boolean_1 = ap_block_state2_io) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) and (ap_const_lv1_1 = and_ln34_fu_268_p2) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1)) or (not(((ap_start = ap_const_logic_0) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) or ((ap_const_boolean_1 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3)) or ((ap_const_boolean_1 = ap_block_state2_io) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) and (cmd_read_read_fu_100_p2 = ap_const_lv8_3) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1)))) then 
                clear_flag <= ap_const_lv1_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((cmd_read_read_fu_100_p2 = ap_const_lv8_3)) and not((cmd_read_read_fu_100_p2 = ap_const_lv8_1)) and not((cmd_read_read_fu_100_p2 = ap_const_lv8_2)) and not(((ap_start = ap_const_logic_0) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) or ((ap_const_boolean_1 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3)) or ((ap_const_boolean_1 = ap_block_state2_io) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                and_ln34_reg_299 <= and_ln34_fu_268_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_1 = ap_CS_iter10_fsm_state11))) then
                and_ln34_reg_299_pp0_iter10_reg <= and_ln34_reg_299_pp0_iter9_reg;
                clear_flag_load_reg_283_pp0_iter10_reg <= clear_flag_load_reg_283_pp0_iter9_reg;
                cmd_read_reg_274_pp0_iter10_reg <= cmd_read_reg_274_pp0_iter9_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_1 = ap_CS_iter11_fsm_state12))) then
                and_ln34_reg_299_pp0_iter11_reg <= and_ln34_reg_299_pp0_iter10_reg;
                clear_flag_load_reg_283_pp0_iter11_reg <= clear_flag_load_reg_283_pp0_iter10_reg;
                cmd_read_reg_274_pp0_iter11_reg <= cmd_read_reg_274_pp0_iter10_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_1 = ap_CS_iter12_fsm_state13))) then
                and_ln34_reg_299_pp0_iter12_reg <= and_ln34_reg_299_pp0_iter11_reg;
                clear_flag_load_reg_283_pp0_iter12_reg <= clear_flag_load_reg_283_pp0_iter11_reg;
                cmd_read_reg_274_pp0_iter12_reg <= cmd_read_reg_274_pp0_iter11_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_1 = ap_CS_iter13_fsm_state14))) then
                and_ln34_reg_299_pp0_iter13_reg <= and_ln34_reg_299_pp0_iter12_reg;
                clear_flag_load_reg_283_pp0_iter13_reg <= clear_flag_load_reg_283_pp0_iter12_reg;
                cmd_read_reg_274_pp0_iter13_reg <= cmd_read_reg_274_pp0_iter12_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) or ((ap_const_boolean_1 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                and_ln34_reg_299_pp0_iter1_reg <= and_ln34_reg_299;
                clear_flag_load_reg_283_pp0_iter1_reg <= clear_flag_load_reg_283;
                cmd_read_reg_274_pp0_iter1_reg <= cmd_read_reg_274;
                gmem_addr_1_reg_287_pp0_iter1_reg <= gmem_addr_1_reg_287;
                wdata_read_reg_278_pp0_iter1_reg <= wdata_read_reg_278;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state3_io) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then
                and_ln34_reg_299_pp0_iter2_reg <= and_ln34_reg_299_pp0_iter1_reg;
                clear_flag_load_reg_283_pp0_iter2_reg <= clear_flag_load_reg_283_pp0_iter1_reg;
                cmd_read_reg_274_pp0_iter2_reg <= cmd_read_reg_274_pp0_iter1_reg;
                gmem_addr_1_reg_287_pp0_iter2_reg <= gmem_addr_1_reg_287_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter3_fsm_state4))) then
                and_ln34_reg_299_pp0_iter3_reg <= and_ln34_reg_299_pp0_iter2_reg;
                clear_flag_load_reg_283_pp0_iter3_reg <= clear_flag_load_reg_283_pp0_iter2_reg;
                cmd_read_reg_274_pp0_iter3_reg <= cmd_read_reg_274_pp0_iter2_reg;
                gmem_addr_1_reg_287_pp0_iter3_reg <= gmem_addr_1_reg_287_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter4_fsm_state5))) then
                and_ln34_reg_299_pp0_iter4_reg <= and_ln34_reg_299_pp0_iter3_reg;
                clear_flag_load_reg_283_pp0_iter4_reg <= clear_flag_load_reg_283_pp0_iter3_reg;
                cmd_read_reg_274_pp0_iter4_reg <= cmd_read_reg_274_pp0_iter3_reg;
                gmem_addr_1_reg_287_pp0_iter4_reg <= gmem_addr_1_reg_287_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter5_fsm_state6))) then
                and_ln34_reg_299_pp0_iter5_reg <= and_ln34_reg_299_pp0_iter4_reg;
                clear_flag_load_reg_283_pp0_iter5_reg <= clear_flag_load_reg_283_pp0_iter4_reg;
                cmd_read_reg_274_pp0_iter5_reg <= cmd_read_reg_274_pp0_iter4_reg;
                gmem_addr_1_reg_287_pp0_iter5_reg <= gmem_addr_1_reg_287_pp0_iter4_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter6_fsm_state7))) then
                and_ln34_reg_299_pp0_iter6_reg <= and_ln34_reg_299_pp0_iter5_reg;
                clear_flag_load_reg_283_pp0_iter6_reg <= clear_flag_load_reg_283_pp0_iter5_reg;
                cmd_read_reg_274_pp0_iter6_reg <= cmd_read_reg_274_pp0_iter5_reg;
                gmem_addr_1_reg_287_pp0_iter6_reg <= gmem_addr_1_reg_287_pp0_iter5_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter7_fsm_state8))) then
                and_ln34_reg_299_pp0_iter7_reg <= and_ln34_reg_299_pp0_iter6_reg;
                clear_flag_load_reg_283_pp0_iter7_reg <= clear_flag_load_reg_283_pp0_iter6_reg;
                cmd_read_reg_274_pp0_iter7_reg <= cmd_read_reg_274_pp0_iter6_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_1 = ap_CS_iter8_fsm_state9))) then
                and_ln34_reg_299_pp0_iter8_reg <= and_ln34_reg_299_pp0_iter7_reg;
                clear_flag_load_reg_283_pp0_iter8_reg <= clear_flag_load_reg_283_pp0_iter7_reg;
                cmd_read_reg_274_pp0_iter8_reg <= cmd_read_reg_274_pp0_iter7_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_1 = ap_CS_iter9_fsm_state10))) then
                and_ln34_reg_299_pp0_iter9_reg <= and_ln34_reg_299_pp0_iter8_reg;
                clear_flag_load_reg_283_pp0_iter9_reg <= clear_flag_load_reg_283_pp0_iter8_reg;
                cmd_read_reg_274_pp0_iter9_reg <= cmd_read_reg_274_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) or ((ap_const_boolean_1 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3)) or ((ap_const_boolean_1 = ap_block_state2_io) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                clear_flag_load_reg_283 <= clear_flag;
                cmd_read_reg_274 <= cmd;
                wdata_read_reg_278 <= wdata;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) or ((ap_const_boolean_1 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3)) or ((ap_const_boolean_1 = ap_block_state2_io) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) and (clear_flag_load_load_fu_182_p1 = ap_const_lv1_0) and (cmd_read_read_fu_100_p2 = ap_const_lv8_2) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                gmem_addr_1_reg_287 <= sext_ln324_1_fu_214_p1(32 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) or ((ap_const_boolean_1 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3)) or ((ap_const_boolean_1 = ap_block_state2_io) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) and (clear_flag_load_load_fu_182_p1 = ap_const_lv1_0) and (cmd_read_read_fu_100_p2 = ap_const_lv8_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                gmem_addr_reg_293 <= sext_ln324_fu_252_p1(32 - 1 downto 0);
            end if;
        end if;
    end process;

    ap_NS_iter0_fsm_assign_proc : process (ap_start, ap_CS_iter0_fsm, gmem_RVALID, gmem_BVALID, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3, ap_predicate_op69_writeresp_state8, ap_block_state8_io, ap_CS_iter7_fsm_state8, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        case ap_CS_iter0_fsm is
            when ap_ST_iter0_fsm_state1 => 
                ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            when others =>  
                ap_NS_iter0_fsm <= "X";
        end case;
    end process;

    ap_NS_iter1_fsm_assign_proc : process (ap_start, ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm, gmem_RVALID, gmem_BVALID, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3, ap_predicate_op69_writeresp_state8, ap_block_state8_io, ap_CS_iter7_fsm_state8, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        case ap_CS_iter1_fsm is
            when ap_ST_iter1_fsm_state2 => 
                if ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) or ((ap_const_boolean_1 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3)))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                elsif ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) or ((ap_const_boolean_1 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3)))) and ((ap_const_logic_0 = ap_CS_iter0_fsm_state1) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                end if;
            when ap_ST_iter1_fsm_state0 => 
                if ((not(((ap_start = ap_const_logic_0) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) or ((ap_const_boolean_1 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3)) or ((ap_const_boolean_1 = ap_block_state2_io) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter1_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter2_fsm_assign_proc : process (ap_CS_iter2_fsm, gmem_RVALID, gmem_BVALID, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3, ap_predicate_op69_writeresp_state8, ap_block_state8_io, ap_CS_iter7_fsm_state8, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        case ap_CS_iter2_fsm is
            when ap_ST_iter2_fsm_state3 => 
                if ((not(((ap_const_boolean_1 = ap_block_state3_io) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and (ap_const_boolean_0 = ap_block_state2_io) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                elsif ((not(((ap_const_boolean_1 = ap_block_state3_io) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and ((ap_const_logic_0 = ap_CS_iter1_fsm_state2) or ((ap_const_boolean_1 = ap_block_state2_io) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state0;
                else
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                end if;
            when ap_ST_iter2_fsm_state0 => 
                if ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) or ((ap_const_boolean_1 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                else
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter2_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter3_fsm_assign_proc : process (ap_CS_iter3_fsm, gmem_RVALID, gmem_BVALID, ap_block_state3_io, ap_CS_iter2_fsm_state3, ap_predicate_op69_writeresp_state8, ap_block_state8_io, ap_CS_iter7_fsm_state8, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        case ap_CS_iter3_fsm is
            when ap_ST_iter3_fsm_state4 => 
                if ((not((((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and (ap_const_boolean_0 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then
                    ap_NS_iter3_fsm <= ap_ST_iter3_fsm_state4;
                elsif ((not((((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and ((ap_const_logic_0 = ap_CS_iter2_fsm_state3) or ((ap_const_boolean_1 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))))) then
                    ap_NS_iter3_fsm <= ap_ST_iter3_fsm_state0;
                else
                    ap_NS_iter3_fsm <= ap_ST_iter3_fsm_state4;
                end if;
            when ap_ST_iter3_fsm_state0 => 
                if ((not(((ap_const_boolean_1 = ap_block_state3_io) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then
                    ap_NS_iter3_fsm <= ap_ST_iter3_fsm_state4;
                else
                    ap_NS_iter3_fsm <= ap_ST_iter3_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter3_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter4_fsm_assign_proc : process (ap_CS_iter4_fsm, gmem_RVALID, gmem_BVALID, ap_CS_iter3_fsm_state4, ap_predicate_op69_writeresp_state8, ap_block_state8_io, ap_CS_iter7_fsm_state8, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        case ap_CS_iter4_fsm is
            when ap_ST_iter4_fsm_state5 => 
                if ((not((((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter3_fsm_state4))) then
                    ap_NS_iter4_fsm <= ap_ST_iter4_fsm_state5;
                elsif ((not((((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and (ap_const_logic_0 = ap_CS_iter3_fsm_state4))) then
                    ap_NS_iter4_fsm <= ap_ST_iter4_fsm_state0;
                else
                    ap_NS_iter4_fsm <= ap_ST_iter4_fsm_state5;
                end if;
            when ap_ST_iter4_fsm_state0 => 
                if ((not((((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter3_fsm_state4))) then
                    ap_NS_iter4_fsm <= ap_ST_iter4_fsm_state5;
                else
                    ap_NS_iter4_fsm <= ap_ST_iter4_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter4_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter5_fsm_assign_proc : process (ap_CS_iter5_fsm, gmem_RVALID, gmem_BVALID, ap_CS_iter4_fsm_state5, ap_predicate_op69_writeresp_state8, ap_block_state8_io, ap_CS_iter7_fsm_state8, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        case ap_CS_iter5_fsm is
            when ap_ST_iter5_fsm_state6 => 
                if ((not((((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter4_fsm_state5))) then
                    ap_NS_iter5_fsm <= ap_ST_iter5_fsm_state6;
                elsif ((not((((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and (ap_const_logic_0 = ap_CS_iter4_fsm_state5))) then
                    ap_NS_iter5_fsm <= ap_ST_iter5_fsm_state0;
                else
                    ap_NS_iter5_fsm <= ap_ST_iter5_fsm_state6;
                end if;
            when ap_ST_iter5_fsm_state0 => 
                if ((not((((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter4_fsm_state5))) then
                    ap_NS_iter5_fsm <= ap_ST_iter5_fsm_state6;
                else
                    ap_NS_iter5_fsm <= ap_ST_iter5_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter5_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter6_fsm_assign_proc : process (ap_CS_iter6_fsm, gmem_RVALID, gmem_BVALID, ap_CS_iter5_fsm_state6, ap_predicate_op69_writeresp_state8, ap_block_state8_io, ap_CS_iter7_fsm_state8, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        case ap_CS_iter6_fsm is
            when ap_ST_iter6_fsm_state7 => 
                if ((not((((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter5_fsm_state6))) then
                    ap_NS_iter6_fsm <= ap_ST_iter6_fsm_state7;
                elsif ((not((((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and (ap_const_logic_0 = ap_CS_iter5_fsm_state6))) then
                    ap_NS_iter6_fsm <= ap_ST_iter6_fsm_state0;
                else
                    ap_NS_iter6_fsm <= ap_ST_iter6_fsm_state7;
                end if;
            when ap_ST_iter6_fsm_state0 => 
                if ((not((((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter5_fsm_state6))) then
                    ap_NS_iter6_fsm <= ap_ST_iter6_fsm_state7;
                else
                    ap_NS_iter6_fsm <= ap_ST_iter6_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter6_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter7_fsm_assign_proc : process (ap_CS_iter7_fsm, gmem_RVALID, gmem_BVALID, ap_CS_iter6_fsm_state7, ap_predicate_op69_writeresp_state8, ap_block_state8_io, ap_CS_iter7_fsm_state8, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        case ap_CS_iter7_fsm is
            when ap_ST_iter7_fsm_state8 => 
                if ((not(((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter6_fsm_state7))) then
                    ap_NS_iter7_fsm <= ap_ST_iter7_fsm_state8;
                elsif ((not(((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) and (ap_const_logic_0 = ap_CS_iter6_fsm_state7))) then
                    ap_NS_iter7_fsm <= ap_ST_iter7_fsm_state0;
                else
                    ap_NS_iter7_fsm <= ap_ST_iter7_fsm_state8;
                end if;
            when ap_ST_iter7_fsm_state0 => 
                if ((not((((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter6_fsm_state7))) then
                    ap_NS_iter7_fsm <= ap_ST_iter7_fsm_state8;
                else
                    ap_NS_iter7_fsm <= ap_ST_iter7_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter7_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter8_fsm_assign_proc : process (ap_CS_iter8_fsm, gmem_RVALID, gmem_BVALID, ap_predicate_op69_writeresp_state8, ap_block_state8_io, ap_CS_iter7_fsm_state8, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        case ap_CS_iter8_fsm is
            when ap_ST_iter8_fsm_state9 => 
                if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and not(((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter7_fsm_state8))) then
                    ap_NS_iter8_fsm <= ap_ST_iter8_fsm_state9;
                elsif ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and ((ap_const_logic_0 = ap_CS_iter7_fsm_state8) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0))))))) then
                    ap_NS_iter8_fsm <= ap_ST_iter8_fsm_state0;
                else
                    ap_NS_iter8_fsm <= ap_ST_iter8_fsm_state9;
                end if;
            when ap_ST_iter8_fsm_state0 => 
                if ((not(((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter7_fsm_state8))) then
                    ap_NS_iter8_fsm <= ap_ST_iter8_fsm_state9;
                else
                    ap_NS_iter8_fsm <= ap_ST_iter8_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter8_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter9_fsm_assign_proc : process (ap_CS_iter9_fsm, gmem_RVALID, ap_CS_iter8_fsm_state9, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        case ap_CS_iter9_fsm is
            when ap_ST_iter9_fsm_state10 => 
                if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_1 = ap_CS_iter8_fsm_state9))) then
                    ap_NS_iter9_fsm <= ap_ST_iter9_fsm_state10;
                elsif ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_0 = ap_CS_iter8_fsm_state9))) then
                    ap_NS_iter9_fsm <= ap_ST_iter9_fsm_state0;
                else
                    ap_NS_iter9_fsm <= ap_ST_iter9_fsm_state10;
                end if;
            when ap_ST_iter9_fsm_state0 => 
                if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_1 = ap_CS_iter8_fsm_state9))) then
                    ap_NS_iter9_fsm <= ap_ST_iter9_fsm_state10;
                else
                    ap_NS_iter9_fsm <= ap_ST_iter9_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter9_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter10_fsm_assign_proc : process (ap_CS_iter10_fsm, gmem_RVALID, ap_CS_iter9_fsm_state10, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        case ap_CS_iter10_fsm is
            when ap_ST_iter10_fsm_state11 => 
                if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_1 = ap_CS_iter9_fsm_state10))) then
                    ap_NS_iter10_fsm <= ap_ST_iter10_fsm_state11;
                elsif ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_0 = ap_CS_iter9_fsm_state10))) then
                    ap_NS_iter10_fsm <= ap_ST_iter10_fsm_state0;
                else
                    ap_NS_iter10_fsm <= ap_ST_iter10_fsm_state11;
                end if;
            when ap_ST_iter10_fsm_state0 => 
                if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_1 = ap_CS_iter9_fsm_state10))) then
                    ap_NS_iter10_fsm <= ap_ST_iter10_fsm_state11;
                else
                    ap_NS_iter10_fsm <= ap_ST_iter10_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter10_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter11_fsm_assign_proc : process (ap_CS_iter11_fsm, gmem_RVALID, ap_CS_iter10_fsm_state11, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        case ap_CS_iter11_fsm is
            when ap_ST_iter11_fsm_state12 => 
                if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_1 = ap_CS_iter10_fsm_state11))) then
                    ap_NS_iter11_fsm <= ap_ST_iter11_fsm_state12;
                elsif ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_0 = ap_CS_iter10_fsm_state11))) then
                    ap_NS_iter11_fsm <= ap_ST_iter11_fsm_state0;
                else
                    ap_NS_iter11_fsm <= ap_ST_iter11_fsm_state12;
                end if;
            when ap_ST_iter11_fsm_state0 => 
                if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_1 = ap_CS_iter10_fsm_state11))) then
                    ap_NS_iter11_fsm <= ap_ST_iter11_fsm_state12;
                else
                    ap_NS_iter11_fsm <= ap_ST_iter11_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter11_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter12_fsm_assign_proc : process (ap_CS_iter12_fsm, gmem_RVALID, ap_CS_iter11_fsm_state12, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        case ap_CS_iter12_fsm is
            when ap_ST_iter12_fsm_state13 => 
                if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_1 = ap_CS_iter11_fsm_state12))) then
                    ap_NS_iter12_fsm <= ap_ST_iter12_fsm_state13;
                elsif ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_0 = ap_CS_iter11_fsm_state12))) then
                    ap_NS_iter12_fsm <= ap_ST_iter12_fsm_state0;
                else
                    ap_NS_iter12_fsm <= ap_ST_iter12_fsm_state13;
                end if;
            when ap_ST_iter12_fsm_state0 => 
                if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_1 = ap_CS_iter11_fsm_state12))) then
                    ap_NS_iter12_fsm <= ap_ST_iter12_fsm_state13;
                else
                    ap_NS_iter12_fsm <= ap_ST_iter12_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter12_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter13_fsm_assign_proc : process (ap_CS_iter13_fsm, gmem_RVALID, ap_CS_iter12_fsm_state13, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        case ap_CS_iter13_fsm is
            when ap_ST_iter13_fsm_state14 => 
                if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_1 = ap_CS_iter12_fsm_state13))) then
                    ap_NS_iter13_fsm <= ap_ST_iter13_fsm_state14;
                elsif ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_0 = ap_CS_iter12_fsm_state13))) then
                    ap_NS_iter13_fsm <= ap_ST_iter13_fsm_state0;
                else
                    ap_NS_iter13_fsm <= ap_ST_iter13_fsm_state14;
                end if;
            when ap_ST_iter13_fsm_state0 => 
                if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_1 = ap_CS_iter12_fsm_state13))) then
                    ap_NS_iter13_fsm <= ap_ST_iter13_fsm_state14;
                else
                    ap_NS_iter13_fsm <= ap_ST_iter13_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter13_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter14_fsm_assign_proc : process (ap_CS_iter14_fsm, gmem_RVALID, ap_CS_iter13_fsm_state14, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        case ap_CS_iter14_fsm is
            when ap_ST_iter14_fsm_state15 => 
                if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_iter13_fsm_state14))) then
                    ap_NS_iter14_fsm <= ap_ST_iter14_fsm_state15;
                elsif ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0))) and (ap_const_logic_0 = ap_CS_iter13_fsm_state14))) then
                    ap_NS_iter14_fsm <= ap_ST_iter14_fsm_state0;
                else
                    ap_NS_iter14_fsm <= ap_ST_iter14_fsm_state15;
                end if;
            when ap_ST_iter14_fsm_state0 => 
                if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) and (ap_const_logic_1 = ap_CS_iter13_fsm_state14))) then
                    ap_NS_iter14_fsm <= ap_ST_iter14_fsm_state15;
                else
                    ap_NS_iter14_fsm <= ap_ST_iter14_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter14_fsm <= "XX";
        end case;
    end process;
    add_ln324_1_fu_198_p2 <= std_logic_vector(unsigned(zext_ln324_1_fu_194_p1) + unsigned(AXI));
    add_ln324_fu_236_p2 <= std_logic_vector(unsigned(zext_ln324_fu_232_p1) + unsigned(AXI));
    and_ln34_fu_268_p2 <= (icmp_ln874_fu_262_p2 and clear_flag);
    ap_CS_iter0_fsm_state1 <= ap_CS_iter0_fsm(0);
    ap_CS_iter10_fsm_state0 <= ap_CS_iter10_fsm(0);
    ap_CS_iter10_fsm_state11 <= ap_CS_iter10_fsm(1);
    ap_CS_iter11_fsm_state0 <= ap_CS_iter11_fsm(0);
    ap_CS_iter11_fsm_state12 <= ap_CS_iter11_fsm(1);
    ap_CS_iter12_fsm_state0 <= ap_CS_iter12_fsm(0);
    ap_CS_iter12_fsm_state13 <= ap_CS_iter12_fsm(1);
    ap_CS_iter13_fsm_state0 <= ap_CS_iter13_fsm(0);
    ap_CS_iter13_fsm_state14 <= ap_CS_iter13_fsm(1);
    ap_CS_iter14_fsm_state0 <= ap_CS_iter14_fsm(0);
    ap_CS_iter14_fsm_state15 <= ap_CS_iter14_fsm(1);
    ap_CS_iter1_fsm_state0 <= ap_CS_iter1_fsm(0);
    ap_CS_iter1_fsm_state2 <= ap_CS_iter1_fsm(1);
    ap_CS_iter2_fsm_state0 <= ap_CS_iter2_fsm(0);
    ap_CS_iter2_fsm_state3 <= ap_CS_iter2_fsm(1);
    ap_CS_iter3_fsm_state0 <= ap_CS_iter3_fsm(0);
    ap_CS_iter3_fsm_state4 <= ap_CS_iter3_fsm(1);
    ap_CS_iter4_fsm_state0 <= ap_CS_iter4_fsm(0);
    ap_CS_iter4_fsm_state5 <= ap_CS_iter4_fsm(1);
    ap_CS_iter5_fsm_state0 <= ap_CS_iter5_fsm(0);
    ap_CS_iter5_fsm_state6 <= ap_CS_iter5_fsm(1);
    ap_CS_iter6_fsm_state0 <= ap_CS_iter6_fsm(0);
    ap_CS_iter6_fsm_state7 <= ap_CS_iter6_fsm(1);
    ap_CS_iter7_fsm_state0 <= ap_CS_iter7_fsm(0);
    ap_CS_iter7_fsm_state8 <= ap_CS_iter7_fsm(1);
    ap_CS_iter8_fsm_state0 <= ap_CS_iter8_fsm(0);
    ap_CS_iter8_fsm_state9 <= ap_CS_iter8_fsm(1);
    ap_CS_iter9_fsm_state0 <= ap_CS_iter9_fsm(0);
    ap_CS_iter9_fsm_state10 <= ap_CS_iter9_fsm(1);
        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state15_pp0_stage0_iter14_assign_proc : process(gmem_RVALID, ap_predicate_op76_read_state15)
    begin
                ap_block_state15_pp0_stage0_iter14 <= ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start = ap_const_logic_0);
    end process;


    ap_block_state2_io_assign_proc : process(gmem_AWREADY, ap_predicate_op62_writereq_state2)
    begin
                ap_block_state2_io <= ((ap_predicate_op62_writereq_state2 = ap_const_boolean_1) and (gmem_AWREADY = ap_const_logic_0));
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_io_assign_proc : process(gmem_WREADY, ap_predicate_op63_write_state3)
    begin
                ap_block_state3_io <= ((ap_predicate_op63_write_state3 = ap_const_boolean_1) and (gmem_WREADY = ap_const_logic_0));
    end process;

        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_io_assign_proc : process(gmem_ARREADY, ap_predicate_op68_readreq_state8)
    begin
                ap_block_state8_io <= ((ap_predicate_op68_readreq_state8 = ap_const_boolean_1) and (gmem_ARREADY = ap_const_logic_0));
    end process;


    ap_block_state8_pp0_stage0_iter7_assign_proc : process(gmem_BVALID, ap_predicate_op69_writeresp_state8)
    begin
                ap_block_state8_pp0_stage0_iter7 <= ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0));
    end process;

        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_568_assign_proc : process(gmem_RVALID, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
                ap_condition_568 <= (not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15));
    end process;


    ap_condition_593_assign_proc : process(cmd_read_reg_274_pp0_iter13_reg, and_ln34_reg_299_pp0_iter13_reg)
    begin
                ap_condition_593 <= (not((cmd_read_reg_274_pp0_iter13_reg = ap_const_lv8_3)) and not((cmd_read_reg_274_pp0_iter13_reg = ap_const_lv8_1)) and not((cmd_read_reg_274_pp0_iter13_reg = ap_const_lv8_2)) and (ap_const_lv1_1 = and_ln34_reg_299_pp0_iter13_reg));
    end process;


    ap_done_assign_proc : process(gmem_RVALID, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state0, ap_CS_iter2_fsm_state0, ap_CS_iter3_fsm_state0, ap_CS_iter4_fsm_state0, ap_CS_iter5_fsm_state0, ap_CS_iter6_fsm_state0, ap_CS_iter7_fsm_state0, ap_CS_iter8_fsm_state0, ap_CS_iter9_fsm_state0, ap_CS_iter10_fsm_state0, ap_CS_iter11_fsm_state0, ap_CS_iter12_fsm_state0, ap_CS_iter13_fsm_state0, ap_CS_iter14_fsm_state0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter6_fsm_state0) and (ap_const_logic_1 = ap_CS_iter5_fsm_state0) and (ap_const_logic_1 = ap_CS_iter4_fsm_state0) and (ap_const_logic_1 = ap_CS_iter3_fsm_state0) and (ap_const_logic_1 = ap_CS_iter2_fsm_state0) and (ap_const_logic_1 = ap_CS_iter1_fsm_state0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_const_logic_1 = ap_CS_iter14_fsm_state0) and (ap_const_logic_1 = ap_CS_iter13_fsm_state0) and (ap_const_logic_1 = ap_CS_iter12_fsm_state0) and (ap_const_logic_1 = ap_CS_iter11_fsm_state0) and (ap_const_logic_1 = ap_CS_iter10_fsm_state0) and (ap_const_logic_1 = ap_CS_iter9_fsm_state0) and (ap_const_logic_1 = ap_CS_iter8_fsm_state0) and (ap_const_logic_1 = ap_CS_iter7_fsm_state0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op62_writereq_state2_assign_proc : process(cmd_read_reg_274, clear_flag_load_reg_283)
    begin
                ap_predicate_op62_writereq_state2 <= ((clear_flag_load_reg_283 = ap_const_lv1_0) and (cmd_read_reg_274 = ap_const_lv8_1));
    end process;


    ap_predicate_op63_write_state3_assign_proc : process(cmd_read_reg_274_pp0_iter1_reg, clear_flag_load_reg_283_pp0_iter1_reg)
    begin
                ap_predicate_op63_write_state3 <= ((clear_flag_load_reg_283_pp0_iter1_reg = ap_const_lv1_0) and (cmd_read_reg_274_pp0_iter1_reg = ap_const_lv8_1));
    end process;


    ap_predicate_op68_readreq_state8_assign_proc : process(cmd_read_reg_274_pp0_iter6_reg, clear_flag_load_reg_283_pp0_iter6_reg)
    begin
                ap_predicate_op68_readreq_state8 <= ((clear_flag_load_reg_283_pp0_iter6_reg = ap_const_lv1_0) and (cmd_read_reg_274_pp0_iter6_reg = ap_const_lv8_2));
    end process;


    ap_predicate_op69_writeresp_state8_assign_proc : process(cmd_read_reg_274_pp0_iter6_reg, clear_flag_load_reg_283_pp0_iter6_reg)
    begin
                ap_predicate_op69_writeresp_state8 <= ((clear_flag_load_reg_283_pp0_iter6_reg = ap_const_lv1_0) and (cmd_read_reg_274_pp0_iter6_reg = ap_const_lv8_1));
    end process;


    ap_predicate_op76_read_state15_assign_proc : process(cmd_read_reg_274_pp0_iter13_reg, clear_flag_load_reg_283_pp0_iter13_reg)
    begin
                ap_predicate_op76_read_state15 <= ((clear_flag_load_reg_283_pp0_iter13_reg = ap_const_lv1_0) and (cmd_read_reg_274_pp0_iter13_reg = ap_const_lv8_2));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_iter0_fsm_state1, gmem_RVALID, gmem_BVALID, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3, ap_predicate_op69_writeresp_state8, ap_block_state8_io, ap_CS_iter7_fsm_state8, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        if ((not(((ap_start = ap_const_logic_0) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) or ((ap_const_boolean_1 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3)) or ((ap_const_boolean_1 = ap_block_state2_io) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    clear_flag_load_load_fu_182_p1 <= clear_flag;
    cmd_read_read_fu_100_p2 <= cmd;

    gmem_ARVALID_assign_proc : process(gmem_RVALID, gmem_BVALID, ap_predicate_op69_writeresp_state8, ap_predicate_op68_readreq_state8, ap_block_state8_io, ap_CS_iter7_fsm_state8, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) and (ap_predicate_op68_readreq_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter7_fsm_state8))) then 
            gmem_ARVALID <= ap_const_logic_1;
        else 
            gmem_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_AWVALID_assign_proc : process(gmem_RVALID, gmem_BVALID, ap_predicate_op62_writereq_state2, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3, ap_predicate_op69_writeresp_state8, ap_block_state8_io, ap_CS_iter7_fsm_state8, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) or ((ap_const_boolean_1 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3)))) and (ap_predicate_op62_writereq_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            gmem_AWVALID <= ap_const_logic_1;
        else 
            gmem_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_BREADY_assign_proc : process(gmem_RVALID, gmem_BVALID, ap_predicate_op69_writeresp_state8, ap_block_state8_io, ap_CS_iter7_fsm_state8, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))) and (ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter7_fsm_state8))) then 
            gmem_BREADY <= ap_const_logic_1;
        else 
            gmem_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem_RREADY_assign_proc : process(gmem_RVALID, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0))) and (ap_predicate_op76_read_state15 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) then 
            gmem_RREADY <= ap_const_logic_1;
        else 
            gmem_RREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem_WVALID_assign_proc : process(gmem_RVALID, gmem_BVALID, ap_predicate_op63_write_state3, ap_block_state3_io, ap_CS_iter2_fsm_state3, ap_predicate_op69_writeresp_state8, ap_block_state8_io, ap_CS_iter7_fsm_state8, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state3_io) or ((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or ((ap_const_logic_1 = ap_CS_iter7_fsm_state8) and ((ap_const_boolean_1 = ap_block_state8_io) or ((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (gmem_BVALID = ap_const_logic_0)))))) and (ap_predicate_op63_write_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then 
            gmem_WVALID <= ap_const_logic_1;
        else 
            gmem_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_blk_n_AR_assign_proc : process(ap_predicate_op68_readreq_state8, ap_CS_iter7_fsm_state8, m_axi_gmem_ARREADY)
    begin
        if (((ap_predicate_op68_readreq_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter7_fsm_state8))) then 
            gmem_blk_n_AR <= m_axi_gmem_ARREADY;
        else 
            gmem_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_AW_assign_proc : process(ap_predicate_op62_writereq_state2, ap_CS_iter1_fsm_state2, m_axi_gmem_AWREADY)
    begin
        if (((ap_predicate_op62_writereq_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            gmem_blk_n_AW <= m_axi_gmem_AWREADY;
        else 
            gmem_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_B_assign_proc : process(ap_predicate_op69_writeresp_state8, ap_CS_iter7_fsm_state8, m_axi_gmem_BVALID)
    begin
        if (((ap_predicate_op69_writeresp_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter7_fsm_state8))) then 
            gmem_blk_n_B <= m_axi_gmem_BVALID;
        else 
            gmem_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_R_assign_proc : process(ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15, m_axi_gmem_RVALID)
    begin
        if (((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) then 
            gmem_blk_n_R <= m_axi_gmem_RVALID;
        else 
            gmem_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_W_assign_proc : process(ap_predicate_op63_write_state3, ap_CS_iter2_fsm_state3, m_axi_gmem_WREADY)
    begin
        if (((ap_predicate_op63_write_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then 
            gmem_blk_n_W <= m_axi_gmem_WREADY;
        else 
            gmem_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln874_fu_262_p2 <= "1" when (cmd = ap_const_lv8_0) else "0";
    rdata <= gmem_RDATA;

    rdata_ap_vld_assign_proc : process(gmem_RVALID, cmd_read_reg_274_pp0_iter13_reg, clear_flag_load_reg_283_pp0_iter13_reg, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15)
    begin
        if ((not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0))) and (clear_flag_load_reg_283_pp0_iter13_reg = ap_const_lv1_0) and (cmd_read_reg_274_pp0_iter13_reg = ap_const_lv8_2) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15))) then 
            rdata_ap_vld <= ap_const_logic_1;
        else 
            rdata_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln324_1_fu_214_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln324_1_fu_204_p4),64));

        sext_ln324_fu_252_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_242_p4),64));

    shl_ln324_1_fu_186_p3 <= (radd & ap_const_lv2_0);
    shl_ln_fu_224_p3 <= (wadd & ap_const_lv2_0);

    sta_assign_proc : process(cmd_read_reg_274_pp0_iter13_reg, clear_flag_load_reg_283_pp0_iter13_reg, ap_condition_593, ap_condition_568)
    begin
        if ((ap_const_boolean_1 = ap_condition_568)) then
            if ((ap_const_boolean_1 = ap_condition_593)) then 
                sta <= ap_const_lv8_0;
            elsif (((clear_flag_load_reg_283_pp0_iter13_reg = ap_const_lv1_0) and (cmd_read_reg_274_pp0_iter13_reg = ap_const_lv8_1))) then 
                sta <= ap_const_lv8_1;
            elsif (((clear_flag_load_reg_283_pp0_iter13_reg = ap_const_lv1_0) and (cmd_read_reg_274_pp0_iter13_reg = ap_const_lv8_2))) then 
                sta <= ap_const_lv8_2;
            else 
                sta <= "XXXXXXXX";
            end if;
        else 
            sta <= "XXXXXXXX";
        end if; 
    end process;


    sta_ap_vld_assign_proc : process(gmem_RVALID, cmd_read_reg_274_pp0_iter13_reg, clear_flag_load_reg_283_pp0_iter13_reg, ap_predicate_op76_read_state15, ap_CS_iter14_fsm_state15, and_ln34_reg_299_pp0_iter13_reg)
    begin
        if (((not((cmd_read_reg_274_pp0_iter13_reg = ap_const_lv8_3)) and not((cmd_read_reg_274_pp0_iter13_reg = ap_const_lv8_1)) and not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0))) and not((cmd_read_reg_274_pp0_iter13_reg = ap_const_lv8_2)) and (ap_const_lv1_1 = and_ln34_reg_299_pp0_iter13_reg) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or (not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0))) and (clear_flag_load_reg_283_pp0_iter13_reg = ap_const_lv1_0) and (cmd_read_reg_274_pp0_iter13_reg = ap_const_lv8_1) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)) or (not(((ap_predicate_op76_read_state15 = ap_const_boolean_1) and (gmem_RVALID = ap_const_logic_0))) and (clear_flag_load_reg_283_pp0_iter13_reg = ap_const_lv1_0) and (cmd_read_reg_274_pp0_iter13_reg = ap_const_lv8_2) and (ap_const_logic_1 = ap_CS_iter14_fsm_state15)))) then 
            sta_ap_vld <= ap_const_logic_1;
        else 
            sta_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln324_1_fu_204_p4 <= add_ln324_1_fu_198_p2(63 downto 2);
    trunc_ln_fu_242_p4 <= add_ln324_fu_236_p2(63 downto 2);
    zext_ln324_1_fu_194_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln324_1_fu_186_p3),64));
    zext_ln324_fu_232_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_224_p3),64));
end behav;
