// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="parallel_to_AXI_parallel_to_AXI,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7s25-csga324-2,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.807000,HLS_SYN_LAT=14,HLS_SYN_TPT=1,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1002,HLS_SYN_LUT=1035,HLS_VERSION=2020_1}" *)

module parallel_to_AXI (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        wdata,
        wadd,
        rdata,
        rdata_ap_vld,
        radd,
        cmd,
        sta,
        sta_ap_vld,
        AXI
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter4_fsm_state5 = 2'd2;
parameter    ap_ST_iter5_fsm_state6 = 2'd2;
parameter    ap_ST_iter6_fsm_state7 = 2'd2;
parameter    ap_ST_iter7_fsm_state8 = 2'd2;
parameter    ap_ST_iter8_fsm_state9 = 2'd2;
parameter    ap_ST_iter9_fsm_state10 = 2'd2;
parameter    ap_ST_iter10_fsm_state11 = 2'd2;
parameter    ap_ST_iter11_fsm_state12 = 2'd2;
parameter    ap_ST_iter12_fsm_state13 = 2'd2;
parameter    ap_ST_iter13_fsm_state14 = 2'd2;
parameter    ap_ST_iter14_fsm_state15 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;
parameter    ap_ST_iter4_fsm_state0 = 2'd1;
parameter    ap_ST_iter5_fsm_state0 = 2'd1;
parameter    ap_ST_iter6_fsm_state0 = 2'd1;
parameter    ap_ST_iter7_fsm_state0 = 2'd1;
parameter    ap_ST_iter8_fsm_state0 = 2'd1;
parameter    ap_ST_iter9_fsm_state0 = 2'd1;
parameter    ap_ST_iter10_fsm_state0 = 2'd1;
parameter    ap_ST_iter11_fsm_state0 = 2'd1;
parameter    ap_ST_iter12_fsm_state0 = 2'd1;
parameter    ap_ST_iter13_fsm_state0 = 2'd1;
parameter    ap_ST_iter14_fsm_state0 = 2'd1;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input  [31:0] wdata;
input  [31:0] wadd;
output  [31:0] rdata;
output   rdata_ap_vld;
input  [31:0] radd;
input  [7:0] cmd;
output  [7:0] sta;
output   sta_ap_vld;
input  [63:0] AXI;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg rdata_ap_vld;
reg[7:0] sta;
reg sta_ap_vld;

 reg    ap_rst_n_inv;
reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
reg   [1:0] ap_CS_iter4_fsm;
wire    ap_CS_iter4_fsm_state0;
reg   [1:0] ap_CS_iter5_fsm;
wire    ap_CS_iter5_fsm_state0;
reg   [1:0] ap_CS_iter6_fsm;
wire    ap_CS_iter6_fsm_state0;
reg   [1:0] ap_CS_iter7_fsm;
wire    ap_CS_iter7_fsm_state0;
reg   [1:0] ap_CS_iter8_fsm;
wire    ap_CS_iter8_fsm_state0;
reg   [1:0] ap_CS_iter9_fsm;
wire    ap_CS_iter9_fsm_state0;
reg   [1:0] ap_CS_iter10_fsm;
wire    ap_CS_iter10_fsm_state0;
reg   [1:0] ap_CS_iter11_fsm;
wire    ap_CS_iter11_fsm_state0;
reg   [1:0] ap_CS_iter12_fsm;
wire    ap_CS_iter12_fsm_state0;
reg   [1:0] ap_CS_iter13_fsm;
wire    ap_CS_iter13_fsm_state0;
reg   [1:0] ap_CS_iter14_fsm;
wire    ap_CS_iter14_fsm_state0;
reg    ap_block_state1_pp0_stage0_iter0;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire    gmem_RLAST;
wire   [0:0] gmem_RID;
wire   [0:0] gmem_RUSER;
wire   [1:0] gmem_RRESP;
wire    gmem_BVALID;
reg    gmem_BREADY;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
wire    ap_block_state2_pp0_stage0_iter1;
reg   [7:0] cmd_read_reg_274;
reg   [0:0] clear_flag_load_reg_283;
reg    ap_predicate_op62_writereq_state2;
reg    ap_block_state2_io;
wire    ap_CS_iter1_fsm_state2;
wire    ap_block_state3_pp0_stage0_iter2;
reg   [7:0] cmd_read_reg_274_pp0_iter1_reg;
reg   [0:0] clear_flag_load_reg_283_pp0_iter1_reg;
reg    ap_predicate_op63_write_state3;
reg    ap_block_state3_io;
wire    ap_CS_iter2_fsm_state3;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_CS_iter3_fsm_state4;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_CS_iter4_fsm_state5;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_CS_iter5_fsm_state6;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_CS_iter6_fsm_state7;
reg   [7:0] cmd_read_reg_274_pp0_iter6_reg;
reg   [0:0] clear_flag_load_reg_283_pp0_iter6_reg;
reg    ap_predicate_op69_writeresp_state8;
reg    ap_block_state8_pp0_stage0_iter7;
reg    ap_predicate_op68_readreq_state8;
reg    ap_block_state8_io;
wire    ap_CS_iter7_fsm_state8;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_CS_iter8_fsm_state9;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_CS_iter9_fsm_state10;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_CS_iter10_fsm_state11;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_CS_iter11_fsm_state12;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_CS_iter12_fsm_state13;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_CS_iter13_fsm_state14;
reg   [7:0] cmd_read_reg_274_pp0_iter13_reg;
reg   [0:0] clear_flag_load_reg_283_pp0_iter13_reg;
reg    ap_predicate_op76_read_state15;
reg    ap_block_state15_pp0_stage0_iter14;
wire    ap_CS_iter14_fsm_state15;
reg   [0:0] clear_flag;
reg    gmem_blk_n_AW;
reg    gmem_blk_n_W;
reg    gmem_blk_n_B;
reg    gmem_blk_n_AR;
reg    gmem_blk_n_R;
wire   [7:0] cmd_read_read_fu_100_p2;
reg   [7:0] cmd_read_reg_274_pp0_iter2_reg;
reg   [7:0] cmd_read_reg_274_pp0_iter3_reg;
reg   [7:0] cmd_read_reg_274_pp0_iter4_reg;
reg   [7:0] cmd_read_reg_274_pp0_iter5_reg;
reg   [7:0] cmd_read_reg_274_pp0_iter7_reg;
reg   [7:0] cmd_read_reg_274_pp0_iter8_reg;
reg   [7:0] cmd_read_reg_274_pp0_iter9_reg;
reg   [7:0] cmd_read_reg_274_pp0_iter10_reg;
reg   [7:0] cmd_read_reg_274_pp0_iter11_reg;
reg   [7:0] cmd_read_reg_274_pp0_iter12_reg;
reg   [31:0] wdata_read_reg_278;
reg   [31:0] wdata_read_reg_278_pp0_iter1_reg;
wire   [0:0] clear_flag_load_load_fu_182_p1;
reg   [0:0] clear_flag_load_reg_283_pp0_iter2_reg;
reg   [0:0] clear_flag_load_reg_283_pp0_iter3_reg;
reg   [0:0] clear_flag_load_reg_283_pp0_iter4_reg;
reg   [0:0] clear_flag_load_reg_283_pp0_iter5_reg;
reg   [0:0] clear_flag_load_reg_283_pp0_iter7_reg;
reg   [0:0] clear_flag_load_reg_283_pp0_iter8_reg;
reg   [0:0] clear_flag_load_reg_283_pp0_iter9_reg;
reg   [0:0] clear_flag_load_reg_283_pp0_iter10_reg;
reg   [0:0] clear_flag_load_reg_283_pp0_iter11_reg;
reg   [0:0] clear_flag_load_reg_283_pp0_iter12_reg;
reg   [31:0] gmem_addr_1_reg_287;
reg   [31:0] gmem_addr_1_reg_287_pp0_iter1_reg;
reg   [31:0] gmem_addr_1_reg_287_pp0_iter2_reg;
reg   [31:0] gmem_addr_1_reg_287_pp0_iter3_reg;
reg   [31:0] gmem_addr_1_reg_287_pp0_iter4_reg;
reg   [31:0] gmem_addr_1_reg_287_pp0_iter5_reg;
reg   [31:0] gmem_addr_1_reg_287_pp0_iter6_reg;
reg   [31:0] gmem_addr_reg_293;
wire   [0:0] and_ln34_fu_268_p2;
reg   [0:0] and_ln34_reg_299;
reg   [0:0] and_ln34_reg_299_pp0_iter1_reg;
reg   [0:0] and_ln34_reg_299_pp0_iter2_reg;
reg   [0:0] and_ln34_reg_299_pp0_iter3_reg;
reg   [0:0] and_ln34_reg_299_pp0_iter4_reg;
reg   [0:0] and_ln34_reg_299_pp0_iter5_reg;
reg   [0:0] and_ln34_reg_299_pp0_iter6_reg;
reg   [0:0] and_ln34_reg_299_pp0_iter7_reg;
reg   [0:0] and_ln34_reg_299_pp0_iter8_reg;
reg   [0:0] and_ln34_reg_299_pp0_iter9_reg;
reg   [0:0] and_ln34_reg_299_pp0_iter10_reg;
reg   [0:0] and_ln34_reg_299_pp0_iter11_reg;
reg   [0:0] and_ln34_reg_299_pp0_iter12_reg;
reg   [0:0] and_ln34_reg_299_pp0_iter13_reg;
wire  signed [63:0] sext_ln324_1_fu_214_p1;
wire  signed [63:0] sext_ln324_fu_252_p1;
wire   [33:0] shl_ln324_1_fu_186_p3;
wire   [63:0] zext_ln324_1_fu_194_p1;
wire   [63:0] add_ln324_1_fu_198_p2;
wire   [61:0] trunc_ln324_1_fu_204_p4;
wire   [33:0] shl_ln_fu_224_p3;
wire   [63:0] zext_ln324_fu_232_p1;
wire   [63:0] add_ln324_fu_236_p2;
wire   [61:0] trunc_ln_fu_242_p4;
wire   [0:0] icmp_ln874_fu_262_p2;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg   [1:0] ap_NS_iter4_fsm;
reg   [1:0] ap_NS_iter5_fsm;
reg   [1:0] ap_NS_iter6_fsm;
reg   [1:0] ap_NS_iter7_fsm;
reg   [1:0] ap_NS_iter8_fsm;
reg   [1:0] ap_NS_iter9_fsm;
reg   [1:0] ap_NS_iter10_fsm;
reg   [1:0] ap_NS_iter11_fsm;
reg   [1:0] ap_NS_iter12_fsm;
reg   [1:0] ap_NS_iter13_fsm;
reg   [1:0] ap_NS_iter14_fsm;
reg    ap_condition_593;
reg    ap_condition_568;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 ap_CS_iter4_fsm = 2'd1;
#0 ap_CS_iter5_fsm = 2'd1;
#0 ap_CS_iter6_fsm = 2'd1;
#0 ap_CS_iter7_fsm = 2'd1;
#0 ap_CS_iter8_fsm = 2'd1;
#0 ap_CS_iter9_fsm = 2'd1;
#0 ap_CS_iter10_fsm = 2'd1;
#0 ap_CS_iter11_fsm = 2'd1;
#0 ap_CS_iter12_fsm = 2'd1;
#0 ap_CS_iter13_fsm = 2'd1;
#0 ap_CS_iter14_fsm = 2'd1;
#0 clear_flag = 1'd0;
end

parallel_to_AXI_gmem_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_addr_1_reg_287_pp0_iter6_reg),
    .I_ARID(1'd0),
    .I_ARLEN(32'd1),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RID(gmem_RID),
    .I_RUSER(gmem_RUSER),
    .I_RRESP(gmem_RRESP),
    .I_RLAST(gmem_RLAST),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(gmem_addr_reg_293),
    .I_AWID(1'd0),
    .I_AWLEN(32'd1),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(wdata_read_reg_278_pp0_iter1_reg),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd15),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY),
    .I_BRESP(gmem_BRESP),
    .I_BID(gmem_BID),
    .I_BUSER(gmem_BUSER)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter10_fsm <= ap_ST_iter10_fsm_state0;
    end else begin
        ap_CS_iter10_fsm <= ap_NS_iter10_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter11_fsm <= ap_ST_iter11_fsm_state0;
    end else begin
        ap_CS_iter11_fsm <= ap_NS_iter11_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter12_fsm <= ap_ST_iter12_fsm_state0;
    end else begin
        ap_CS_iter12_fsm <= ap_NS_iter12_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter13_fsm <= ap_ST_iter13_fsm_state0;
    end else begin
        ap_CS_iter13_fsm <= ap_NS_iter13_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter14_fsm <= ap_ST_iter14_fsm_state0;
    end else begin
        ap_CS_iter14_fsm <= ap_NS_iter14_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter4_fsm <= ap_ST_iter4_fsm_state0;
    end else begin
        ap_CS_iter4_fsm <= ap_NS_iter4_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter5_fsm <= ap_ST_iter5_fsm_state0;
    end else begin
        ap_CS_iter5_fsm <= ap_NS_iter5_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter6_fsm <= ap_ST_iter6_fsm_state0;
    end else begin
        ap_CS_iter6_fsm <= ap_NS_iter6_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter7_fsm <= ap_ST_iter7_fsm_state0;
    end else begin
        ap_CS_iter7_fsm <= ap_NS_iter7_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter8_fsm <= ap_ST_iter8_fsm_state0;
    end else begin
        ap_CS_iter8_fsm <= ap_NS_iter8_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter9_fsm <= ap_ST_iter9_fsm_state0;
    end else begin
        ap_CS_iter9_fsm <= ap_NS_iter9_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0)))) | ((1'b1 == ap_block_state3_io) & (1'b1 == ap_CS_iter2_fsm_state3)) | ((1'b1 == ap_block_state2_io) & (1'b1 == ap_CS_iter1_fsm_state2))) & (clear_flag_load_load_fu_182_p1 == 1'd0) & (cmd_read_read_fu_100_p2 == 8'd1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_start == 1'b0) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0)))) | ((1'b1 == ap_block_state3_io) & (1'b1 == ap_CS_iter2_fsm_state3)) | ((1'b1 == ap_block_state2_io) & (1'b1 == ap_CS_iter1_fsm_state2))) & (clear_flag_load_load_fu_182_p1 == 1'd0) & (cmd_read_read_fu_100_p2 == 8'd2) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        clear_flag <= 1'd1;
    end else if (((~(cmd_read_read_fu_100_p2 == 8'd3) & ~(cmd_read_read_fu_100_p2 == 8'd1) & ~(cmd_read_read_fu_100_p2 == 8'd2) & ~((ap_start == 1'b0) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0)))) | ((1'b1 == ap_block_state3_io) & (1'b1 == ap_CS_iter2_fsm_state3)) | ((1'b1 == ap_block_state2_io) & (1'b1 == ap_CS_iter1_fsm_state2))) & (1'd1 == and_ln34_fu_268_p2) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_start == 1'b0) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0)))) | ((1'b1 == ap_block_state3_io) & (1'b1 == ap_CS_iter2_fsm_state3)) | ((1'b1 == ap_block_state2_io) & (1'b1 == ap_CS_iter1_fsm_state2))) & (cmd_read_read_fu_100_p2 == 8'd3) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        clear_flag <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(cmd_read_read_fu_100_p2 == 8'd3) & ~(cmd_read_read_fu_100_p2 == 8'd1) & ~(cmd_read_read_fu_100_p2 == 8'd2) & ~((ap_start == 1'b0) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0)))) | ((1'b1 == ap_block_state3_io) & (1'b1 == ap_CS_iter2_fsm_state3)) | ((1'b1 == ap_block_state2_io) & (1'b1 == ap_CS_iter1_fsm_state2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        and_ln34_reg_299 <= and_ln34_fu_268_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b1 == ap_CS_iter10_fsm_state11))) begin
        and_ln34_reg_299_pp0_iter10_reg <= and_ln34_reg_299_pp0_iter9_reg;
        clear_flag_load_reg_283_pp0_iter10_reg <= clear_flag_load_reg_283_pp0_iter9_reg;
        cmd_read_reg_274_pp0_iter10_reg <= cmd_read_reg_274_pp0_iter9_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b1 == ap_CS_iter11_fsm_state12))) begin
        and_ln34_reg_299_pp0_iter11_reg <= and_ln34_reg_299_pp0_iter10_reg;
        clear_flag_load_reg_283_pp0_iter11_reg <= clear_flag_load_reg_283_pp0_iter10_reg;
        cmd_read_reg_274_pp0_iter11_reg <= cmd_read_reg_274_pp0_iter10_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b1 == ap_CS_iter12_fsm_state13))) begin
        and_ln34_reg_299_pp0_iter12_reg <= and_ln34_reg_299_pp0_iter11_reg;
        clear_flag_load_reg_283_pp0_iter12_reg <= clear_flag_load_reg_283_pp0_iter11_reg;
        cmd_read_reg_274_pp0_iter12_reg <= cmd_read_reg_274_pp0_iter11_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b1 == ap_CS_iter13_fsm_state14))) begin
        and_ln34_reg_299_pp0_iter13_reg <= and_ln34_reg_299_pp0_iter12_reg;
        clear_flag_load_reg_283_pp0_iter13_reg <= clear_flag_load_reg_283_pp0_iter12_reg;
        cmd_read_reg_274_pp0_iter13_reg <= cmd_read_reg_274_pp0_iter12_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state2_io) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0)))) | ((1'b1 == ap_block_state3_io) & (1'b1 == ap_CS_iter2_fsm_state3))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        and_ln34_reg_299_pp0_iter1_reg <= and_ln34_reg_299;
        clear_flag_load_reg_283_pp0_iter1_reg <= clear_flag_load_reg_283;
        cmd_read_reg_274_pp0_iter1_reg <= cmd_read_reg_274;
        gmem_addr_1_reg_287_pp0_iter1_reg <= gmem_addr_1_reg_287;
        wdata_read_reg_278_pp0_iter1_reg <= wdata_read_reg_278;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        and_ln34_reg_299_pp0_iter2_reg <= and_ln34_reg_299_pp0_iter1_reg;
        clear_flag_load_reg_283_pp0_iter2_reg <= clear_flag_load_reg_283_pp0_iter1_reg;
        cmd_read_reg_274_pp0_iter2_reg <= cmd_read_reg_274_pp0_iter1_reg;
        gmem_addr_1_reg_287_pp0_iter2_reg <= gmem_addr_1_reg_287_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        and_ln34_reg_299_pp0_iter3_reg <= and_ln34_reg_299_pp0_iter2_reg;
        clear_flag_load_reg_283_pp0_iter3_reg <= clear_flag_load_reg_283_pp0_iter2_reg;
        cmd_read_reg_274_pp0_iter3_reg <= cmd_read_reg_274_pp0_iter2_reg;
        gmem_addr_1_reg_287_pp0_iter3_reg <= gmem_addr_1_reg_287_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        and_ln34_reg_299_pp0_iter4_reg <= and_ln34_reg_299_pp0_iter3_reg;
        clear_flag_load_reg_283_pp0_iter4_reg <= clear_flag_load_reg_283_pp0_iter3_reg;
        cmd_read_reg_274_pp0_iter4_reg <= cmd_read_reg_274_pp0_iter3_reg;
        gmem_addr_1_reg_287_pp0_iter4_reg <= gmem_addr_1_reg_287_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
        and_ln34_reg_299_pp0_iter5_reg <= and_ln34_reg_299_pp0_iter4_reg;
        clear_flag_load_reg_283_pp0_iter5_reg <= clear_flag_load_reg_283_pp0_iter4_reg;
        cmd_read_reg_274_pp0_iter5_reg <= cmd_read_reg_274_pp0_iter4_reg;
        gmem_addr_1_reg_287_pp0_iter5_reg <= gmem_addr_1_reg_287_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & (1'b1 == ap_CS_iter6_fsm_state7))) begin
        and_ln34_reg_299_pp0_iter6_reg <= and_ln34_reg_299_pp0_iter5_reg;
        clear_flag_load_reg_283_pp0_iter6_reg <= clear_flag_load_reg_283_pp0_iter5_reg;
        cmd_read_reg_274_pp0_iter6_reg <= cmd_read_reg_274_pp0_iter5_reg;
        gmem_addr_1_reg_287_pp0_iter6_reg <= gmem_addr_1_reg_287_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state8_io) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))) & (1'b1 == ap_CS_iter7_fsm_state8))) begin
        and_ln34_reg_299_pp0_iter7_reg <= and_ln34_reg_299_pp0_iter6_reg;
        clear_flag_load_reg_283_pp0_iter7_reg <= clear_flag_load_reg_283_pp0_iter6_reg;
        cmd_read_reg_274_pp0_iter7_reg <= cmd_read_reg_274_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b1 == ap_CS_iter8_fsm_state9))) begin
        and_ln34_reg_299_pp0_iter8_reg <= and_ln34_reg_299_pp0_iter7_reg;
        clear_flag_load_reg_283_pp0_iter8_reg <= clear_flag_load_reg_283_pp0_iter7_reg;
        cmd_read_reg_274_pp0_iter8_reg <= cmd_read_reg_274_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b1 == ap_CS_iter9_fsm_state10))) begin
        and_ln34_reg_299_pp0_iter9_reg <= and_ln34_reg_299_pp0_iter8_reg;
        clear_flag_load_reg_283_pp0_iter9_reg <= clear_flag_load_reg_283_pp0_iter8_reg;
        cmd_read_reg_274_pp0_iter9_reg <= cmd_read_reg_274_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0)))) | ((1'b1 == ap_block_state3_io) & (1'b1 == ap_CS_iter2_fsm_state3)) | ((1'b1 == ap_block_state2_io) & (1'b1 == ap_CS_iter1_fsm_state2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        clear_flag_load_reg_283 <= clear_flag;
        cmd_read_reg_274 <= cmd;
        wdata_read_reg_278 <= wdata;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0)))) | ((1'b1 == ap_block_state3_io) & (1'b1 == ap_CS_iter2_fsm_state3)) | ((1'b1 == ap_block_state2_io) & (1'b1 == ap_CS_iter1_fsm_state2))) & (clear_flag_load_load_fu_182_p1 == 1'd0) & (cmd_read_read_fu_100_p2 == 8'd2) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        gmem_addr_1_reg_287 <= sext_ln324_1_fu_214_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0)))) | ((1'b1 == ap_block_state3_io) & (1'b1 == ap_CS_iter2_fsm_state3)) | ((1'b1 == ap_block_state2_io) & (1'b1 == ap_CS_iter1_fsm_state2))) & (clear_flag_load_load_fu_182_p1 == 1'd0) & (cmd_read_read_fu_100_p2 == 8'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        gmem_addr_reg_293 <= sext_ln324_fu_252_p1;
    end
end

always @ (*) begin
    if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0)) & (1'b1 == ap_CS_iter14_fsm_state15))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_iter6_fsm_state0) & (1'b1 == ap_CS_iter5_fsm_state0) & (1'b1 == ap_CS_iter4_fsm_state0) & (1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_CS_iter14_fsm_state0) & (1'b1 == ap_CS_iter13_fsm_state0) & (1'b1 == ap_CS_iter12_fsm_state0) & (1'b1 == ap_CS_iter11_fsm_state0) & (1'b1 == ap_CS_iter10_fsm_state0) & (1'b1 == ap_CS_iter9_fsm_state0) & (1'b1 == ap_CS_iter8_fsm_state0) & (1'b1 == ap_CS_iter7_fsm_state0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0)))) | ((1'b1 == ap_block_state3_io) & (1'b1 == ap_CS_iter2_fsm_state3)) | ((1'b1 == ap_block_state2_io) & (1'b1 == ap_CS_iter1_fsm_state2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state8_io) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))) & (ap_predicate_op68_readreq_state8 == 1'b1) & (1'b1 == ap_CS_iter7_fsm_state8))) begin
        gmem_ARVALID = 1'b1;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0)))) | ((1'b1 == ap_block_state3_io) & (1'b1 == ap_CS_iter2_fsm_state3))) & (ap_predicate_op62_writereq_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        gmem_AWVALID = 1'b1;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state8_io) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))) & (ap_predicate_op69_writeresp_state8 == 1'b1) & (1'b1 == ap_CS_iter7_fsm_state8))) begin
        gmem_BREADY = 1'b1;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0)) & (ap_predicate_op76_read_state15 == 1'b1) & (1'b1 == ap_CS_iter14_fsm_state15))) begin
        gmem_RREADY = 1'b1;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & (ap_predicate_op63_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        gmem_WVALID = 1'b1;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op68_readreq_state8 == 1'b1) & (1'b1 == ap_CS_iter7_fsm_state8))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op62_writereq_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op69_writeresp_state8 == 1'b1) & (1'b1 == ap_CS_iter7_fsm_state8))) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op76_read_state15 == 1'b1) & (1'b1 == ap_CS_iter14_fsm_state15))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op63_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0)) & (clear_flag_load_reg_283_pp0_iter13_reg == 1'd0) & (cmd_read_reg_274_pp0_iter13_reg == 8'd2) & (1'b1 == ap_CS_iter14_fsm_state15))) begin
        rdata_ap_vld = 1'b1;
    end else begin
        rdata_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_568)) begin
        if ((1'b1 == ap_condition_593)) begin
            sta = 8'd0;
        end else if (((clear_flag_load_reg_283_pp0_iter13_reg == 1'd0) & (cmd_read_reg_274_pp0_iter13_reg == 8'd1))) begin
            sta = 8'd1;
        end else if (((clear_flag_load_reg_283_pp0_iter13_reg == 1'd0) & (cmd_read_reg_274_pp0_iter13_reg == 8'd2))) begin
            sta = 8'd2;
        end else begin
            sta = 'bx;
        end
    end else begin
        sta = 'bx;
    end
end

always @ (*) begin
    if (((~(cmd_read_reg_274_pp0_iter13_reg == 8'd3) & ~(cmd_read_reg_274_pp0_iter13_reg == 8'd1) & ~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0)) & ~(cmd_read_reg_274_pp0_iter13_reg == 8'd2) & (1'd1 == and_ln34_reg_299_pp0_iter13_reg) & (1'b1 == ap_CS_iter14_fsm_state15)) | (~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0)) & (clear_flag_load_reg_283_pp0_iter13_reg == 1'd0) & (cmd_read_reg_274_pp0_iter13_reg == 8'd1) & (1'b1 == ap_CS_iter14_fsm_state15)) | (~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0)) & (clear_flag_load_reg_283_pp0_iter13_reg == 1'd0) & (cmd_read_reg_274_pp0_iter13_reg == 8'd2) & (1'b1 == ap_CS_iter14_fsm_state15)))) begin
        sta_ap_vld = 1'b1;
    end else begin
        sta_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_block_state2_io) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0)))) | ((1'b1 == ap_block_state3_io) & (1'b1 == ap_CS_iter2_fsm_state3))) & (ap_start == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_block_state2_io) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0)))) | ((1'b1 == ap_block_state3_io) & (1'b1 == ap_CS_iter2_fsm_state3))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((ap_start == 1'b0) & (1'b1 == ap_CS_iter0_fsm_state1))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_start == 1'b0) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0)))) | ((1'b1 == ap_block_state3_io) & (1'b1 == ap_CS_iter2_fsm_state3)) | ((1'b1 == ap_block_state2_io) & (1'b1 == ap_CS_iter1_fsm_state2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & (1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & ((1'b0 == ap_CS_iter1_fsm_state2) | ((1'b1 == ap_block_state2_io) & (1'b1 == ap_CS_iter1_fsm_state2))))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state2_io) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0)))) | ((1'b1 == ap_block_state3_io) & (1'b1 == ap_CS_iter2_fsm_state3))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~(((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & (1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else if ((~(((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & ((1'b0 == ap_CS_iter2_fsm_state3) | ((1'b1 == ap_block_state3_io) & (1'b1 == ap_CS_iter2_fsm_state3))))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter4_fsm)
        ap_ST_iter4_fsm_state5 : begin
            if ((~(((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else if ((~(((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & (1'b0 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end
        end
        ap_ST_iter4_fsm_state0 : begin
            if ((~(((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter4_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter5_fsm)
        ap_ST_iter5_fsm_state6 : begin
            if ((~(((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else if ((~(((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & (1'b0 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end
        end
        ap_ST_iter5_fsm_state0 : begin
            if ((~(((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter5_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter6_fsm)
        ap_ST_iter6_fsm_state7 : begin
            if ((~(((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state7;
            end else if ((~(((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & (1'b0 == ap_CS_iter5_fsm_state6))) begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state0;
            end else begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state7;
            end
        end
        ap_ST_iter6_fsm_state0 : begin
            if ((~(((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state7;
            end else begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter6_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter7_fsm)
        ap_ST_iter7_fsm_state8 : begin
            if ((~((1'b1 == ap_block_state8_io) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))) & (1'b1 == ap_CS_iter6_fsm_state7))) begin
                ap_NS_iter7_fsm = ap_ST_iter7_fsm_state8;
            end else if ((~((1'b1 == ap_block_state8_io) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))) & (1'b0 == ap_CS_iter6_fsm_state7))) begin
                ap_NS_iter7_fsm = ap_ST_iter7_fsm_state0;
            end else begin
                ap_NS_iter7_fsm = ap_ST_iter7_fsm_state8;
            end
        end
        ap_ST_iter7_fsm_state0 : begin
            if ((~(((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))) & (1'b1 == ap_CS_iter6_fsm_state7))) begin
                ap_NS_iter7_fsm = ap_ST_iter7_fsm_state8;
            end else begin
                ap_NS_iter7_fsm = ap_ST_iter7_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter7_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter8_fsm)
        ap_ST_iter8_fsm_state9 : begin
            if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & ~((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))) & (1'b1 == ap_CS_iter7_fsm_state8))) begin
                ap_NS_iter8_fsm = ap_ST_iter8_fsm_state9;
            end else if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & ((1'b0 == ap_CS_iter7_fsm_state8) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))))))) begin
                ap_NS_iter8_fsm = ap_ST_iter8_fsm_state0;
            end else begin
                ap_NS_iter8_fsm = ap_ST_iter8_fsm_state9;
            end
        end
        ap_ST_iter8_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state8_io) | ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) | ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0))) & (1'b1 == ap_CS_iter7_fsm_state8))) begin
                ap_NS_iter8_fsm = ap_ST_iter8_fsm_state9;
            end else begin
                ap_NS_iter8_fsm = ap_ST_iter8_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter8_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter9_fsm)
        ap_ST_iter9_fsm_state10 : begin
            if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b1 == ap_CS_iter8_fsm_state9))) begin
                ap_NS_iter9_fsm = ap_ST_iter9_fsm_state10;
            end else if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b0 == ap_CS_iter8_fsm_state9))) begin
                ap_NS_iter9_fsm = ap_ST_iter9_fsm_state0;
            end else begin
                ap_NS_iter9_fsm = ap_ST_iter9_fsm_state10;
            end
        end
        ap_ST_iter9_fsm_state0 : begin
            if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b1 == ap_CS_iter8_fsm_state9))) begin
                ap_NS_iter9_fsm = ap_ST_iter9_fsm_state10;
            end else begin
                ap_NS_iter9_fsm = ap_ST_iter9_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter9_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter10_fsm)
        ap_ST_iter10_fsm_state11 : begin
            if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b1 == ap_CS_iter9_fsm_state10))) begin
                ap_NS_iter10_fsm = ap_ST_iter10_fsm_state11;
            end else if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b0 == ap_CS_iter9_fsm_state10))) begin
                ap_NS_iter10_fsm = ap_ST_iter10_fsm_state0;
            end else begin
                ap_NS_iter10_fsm = ap_ST_iter10_fsm_state11;
            end
        end
        ap_ST_iter10_fsm_state0 : begin
            if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b1 == ap_CS_iter9_fsm_state10))) begin
                ap_NS_iter10_fsm = ap_ST_iter10_fsm_state11;
            end else begin
                ap_NS_iter10_fsm = ap_ST_iter10_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter10_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter11_fsm)
        ap_ST_iter11_fsm_state12 : begin
            if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b1 == ap_CS_iter10_fsm_state11))) begin
                ap_NS_iter11_fsm = ap_ST_iter11_fsm_state12;
            end else if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b0 == ap_CS_iter10_fsm_state11))) begin
                ap_NS_iter11_fsm = ap_ST_iter11_fsm_state0;
            end else begin
                ap_NS_iter11_fsm = ap_ST_iter11_fsm_state12;
            end
        end
        ap_ST_iter11_fsm_state0 : begin
            if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b1 == ap_CS_iter10_fsm_state11))) begin
                ap_NS_iter11_fsm = ap_ST_iter11_fsm_state12;
            end else begin
                ap_NS_iter11_fsm = ap_ST_iter11_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter11_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter12_fsm)
        ap_ST_iter12_fsm_state13 : begin
            if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b1 == ap_CS_iter11_fsm_state12))) begin
                ap_NS_iter12_fsm = ap_ST_iter12_fsm_state13;
            end else if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b0 == ap_CS_iter11_fsm_state12))) begin
                ap_NS_iter12_fsm = ap_ST_iter12_fsm_state0;
            end else begin
                ap_NS_iter12_fsm = ap_ST_iter12_fsm_state13;
            end
        end
        ap_ST_iter12_fsm_state0 : begin
            if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b1 == ap_CS_iter11_fsm_state12))) begin
                ap_NS_iter12_fsm = ap_ST_iter12_fsm_state13;
            end else begin
                ap_NS_iter12_fsm = ap_ST_iter12_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter12_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter13_fsm)
        ap_ST_iter13_fsm_state14 : begin
            if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b1 == ap_CS_iter12_fsm_state13))) begin
                ap_NS_iter13_fsm = ap_ST_iter13_fsm_state14;
            end else if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b0 == ap_CS_iter12_fsm_state13))) begin
                ap_NS_iter13_fsm = ap_ST_iter13_fsm_state0;
            end else begin
                ap_NS_iter13_fsm = ap_ST_iter13_fsm_state14;
            end
        end
        ap_ST_iter13_fsm_state0 : begin
            if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b1 == ap_CS_iter12_fsm_state13))) begin
                ap_NS_iter13_fsm = ap_ST_iter13_fsm_state14;
            end else begin
                ap_NS_iter13_fsm = ap_ST_iter13_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter13_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter14_fsm)
        ap_ST_iter14_fsm_state15 : begin
            if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0)) & (1'b1 == ap_CS_iter13_fsm_state14))) begin
                ap_NS_iter14_fsm = ap_ST_iter14_fsm_state15;
            end else if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0)) & (1'b0 == ap_CS_iter13_fsm_state14))) begin
                ap_NS_iter14_fsm = ap_ST_iter14_fsm_state0;
            end else begin
                ap_NS_iter14_fsm = ap_ST_iter14_fsm_state15;
            end
        end
        ap_ST_iter14_fsm_state0 : begin
            if ((~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0) & (1'b1 == ap_CS_iter14_fsm_state15)) & (1'b1 == ap_CS_iter13_fsm_state14))) begin
                ap_NS_iter14_fsm = ap_ST_iter14_fsm_state15;
            end else begin
                ap_NS_iter14_fsm = ap_ST_iter14_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter14_fsm = 'bx;
        end
    endcase
end

assign add_ln324_1_fu_198_p2 = (zext_ln324_1_fu_194_p1 + AXI);

assign add_ln324_fu_236_p2 = (zext_ln324_fu_232_p1 + AXI);

assign and_ln34_fu_268_p2 = (icmp_ln874_fu_262_p2 & clear_flag);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter10_fsm_state0 = ap_CS_iter10_fsm[32'd0];

assign ap_CS_iter10_fsm_state11 = ap_CS_iter10_fsm[32'd1];

assign ap_CS_iter11_fsm_state0 = ap_CS_iter11_fsm[32'd0];

assign ap_CS_iter11_fsm_state12 = ap_CS_iter11_fsm[32'd1];

assign ap_CS_iter12_fsm_state0 = ap_CS_iter12_fsm[32'd0];

assign ap_CS_iter12_fsm_state13 = ap_CS_iter12_fsm[32'd1];

assign ap_CS_iter13_fsm_state0 = ap_CS_iter13_fsm[32'd0];

assign ap_CS_iter13_fsm_state14 = ap_CS_iter13_fsm[32'd1];

assign ap_CS_iter14_fsm_state0 = ap_CS_iter14_fsm[32'd0];

assign ap_CS_iter14_fsm_state15 = ap_CS_iter14_fsm[32'd1];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

assign ap_CS_iter4_fsm_state0 = ap_CS_iter4_fsm[32'd0];

assign ap_CS_iter4_fsm_state5 = ap_CS_iter4_fsm[32'd1];

assign ap_CS_iter5_fsm_state0 = ap_CS_iter5_fsm[32'd0];

assign ap_CS_iter5_fsm_state6 = ap_CS_iter5_fsm[32'd1];

assign ap_CS_iter6_fsm_state0 = ap_CS_iter6_fsm[32'd0];

assign ap_CS_iter6_fsm_state7 = ap_CS_iter6_fsm[32'd1];

assign ap_CS_iter7_fsm_state0 = ap_CS_iter7_fsm[32'd0];

assign ap_CS_iter7_fsm_state8 = ap_CS_iter7_fsm[32'd1];

assign ap_CS_iter8_fsm_state0 = ap_CS_iter8_fsm[32'd0];

assign ap_CS_iter8_fsm_state9 = ap_CS_iter8_fsm[32'd1];

assign ap_CS_iter9_fsm_state0 = ap_CS_iter9_fsm[32'd0];

assign ap_CS_iter9_fsm_state10 = ap_CS_iter9_fsm[32'd1];

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state15_pp0_stage0_iter14 = ((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

always @ (*) begin
    ap_block_state2_io = ((ap_predicate_op62_writereq_state2 == 1'b1) & (gmem_AWREADY == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_io = ((ap_predicate_op63_write_state3 == 1'b1) & (gmem_WREADY == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_io = ((ap_predicate_op68_readreq_state8 == 1'b1) & (gmem_ARREADY == 1'b0));
end

always @ (*) begin
    ap_block_state8_pp0_stage0_iter7 = ((ap_predicate_op69_writeresp_state8 == 1'b1) & (gmem_BVALID == 1'b0));
end

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_568 = (~((ap_predicate_op76_read_state15 == 1'b1) & (gmem_RVALID == 1'b0)) & (1'b1 == ap_CS_iter14_fsm_state15));
end

always @ (*) begin
    ap_condition_593 = (~(cmd_read_reg_274_pp0_iter13_reg == 8'd3) & ~(cmd_read_reg_274_pp0_iter13_reg == 8'd1) & ~(cmd_read_reg_274_pp0_iter13_reg == 8'd2) & (1'd1 == and_ln34_reg_299_pp0_iter13_reg));
end

always @ (*) begin
    ap_predicate_op62_writereq_state2 = ((clear_flag_load_reg_283 == 1'd0) & (cmd_read_reg_274 == 8'd1));
end

always @ (*) begin
    ap_predicate_op63_write_state3 = ((clear_flag_load_reg_283_pp0_iter1_reg == 1'd0) & (cmd_read_reg_274_pp0_iter1_reg == 8'd1));
end

always @ (*) begin
    ap_predicate_op68_readreq_state8 = ((clear_flag_load_reg_283_pp0_iter6_reg == 1'd0) & (cmd_read_reg_274_pp0_iter6_reg == 8'd2));
end

always @ (*) begin
    ap_predicate_op69_writeresp_state8 = ((clear_flag_load_reg_283_pp0_iter6_reg == 1'd0) & (cmd_read_reg_274_pp0_iter6_reg == 8'd1));
end

always @ (*) begin
    ap_predicate_op76_read_state15 = ((clear_flag_load_reg_283_pp0_iter13_reg == 1'd0) & (cmd_read_reg_274_pp0_iter13_reg == 8'd2));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign clear_flag_load_load_fu_182_p1 = clear_flag;

assign cmd_read_read_fu_100_p2 = cmd;

assign icmp_ln874_fu_262_p2 = ((cmd == 8'd0) ? 1'b1 : 1'b0);

assign rdata = gmem_RDATA;

assign sext_ln324_1_fu_214_p1 = $signed(trunc_ln324_1_fu_204_p4);

assign sext_ln324_fu_252_p1 = $signed(trunc_ln_fu_242_p4);

assign shl_ln324_1_fu_186_p3 = {{radd}, {2'd0}};

assign shl_ln_fu_224_p3 = {{wadd}, {2'd0}};

assign trunc_ln324_1_fu_204_p4 = {{add_ln324_1_fu_198_p2[63:2]}};

assign trunc_ln_fu_242_p4 = {{add_ln324_fu_236_p2[63:2]}};

assign zext_ln324_1_fu_194_p1 = shl_ln324_1_fu_186_p3;

assign zext_ln324_fu_232_p1 = shl_ln_fu_224_p3;

endmodule //parallel_to_AXI
